### ISSUE TITLE
Create CFP page on Website

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#100]
This should include:
- Call for Presentations
- Dates for the conference
- Guidelines for prospective speakers (including deadline for submitting recordings)
- Sponsorship programme

**Comment by voborgus** [comment]
this can be a regular event page with a CFP section. example: https://innersourcecommons.org/events/isc-apac-dec-2020/

**Comment by clcoffey** [comment]
Yes, that's what I had in mind too. Just a regular event page with the information in the bullet points included. 

Most of the information can be found in the planning document here: https://docs.google.com/document/d/1WFuvopoMLm0uYIYndJj1vPEaf3eP-0cASqk0R1DG2a0/edit

CFP draft form is here: https://docs.google.com/forms/d/1IanpPLwtmdS5C4m05xrrVmyH4XhO6jf9rRQT8h2XTkg/edit
