### ISSUE TITLE
Changes for the Website

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#107]
### Change the Events Page

As discussed in the Marketing meeting we are looking to change the Events page on the website as follows:
- order the events from closest in date to the furthest (E.g.: 7 Sept Community call; 21 Sept Community Call; Summit; Past Events )
- Change the text on the buttons from Register Now to Open event

### For the entire website:

Adding "CFP is Open" call to action to all website pages:

Insert the code

```
<section class="notice bg-primary text-light">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-12 text-center">
        <a class="text-light" href="http://innersourcecommons.org">Call For Papers</a> is open for InnerSource Commons Summit 2021. Save the dates – 17th November, 2021
      </div>
    </div>
  </div>
</section>
```

To the very end of [header.html](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/layouts/partials/header.html)

**Comment by clcoffey** [comment]
@voborgus Could you help with this? :-)

**Comment by voborgus** [comment]
For sure!
