### ISSUE TITLE
Revive State of InnerSource Survey

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#11]

**Comment by lenucksi** [comment]
Klaas created this document regarding it: 
- https://drive.google.com/drive/folders/15L1R9B5VRMjOfYAVAAsJobMs0HG_Fnd6 
- Mostly: What are the boxes and causalities we want to know about
- What do we want to know about InnerSource in the industry?
- We need Research Questions.

First
- Brainstorm (see doc above)
Second
- Curate and Group by relatedness
Third
- Create survey and roll out (Google Forms, Lime Survey) (target by the summit in September)
- Run it
Fourth
- Analysis
- Write-Up

- Use Event and other events with sponsors to get more participants.
- Do descriptive first and then give the inferential approach a try as a second step.

**Comment by spier** [comment]
Note from last meeting: Klaas volunteered to drive this task, but he isn't part of this github project yet, so we cannot assign the issue to him.

**Comment by lenucksi** [comment]
> Note from last meeting: Klaas volunteered to drive this task, but he isn't part of this github project yet, so we cannot assign the issue to him.

Just reached out to @kjs via mail to remind him to accept the GitHub invite. Once he accepts, we can put him on the ticket and mention him easier.

**Comment by spier** [comment]
Hoping to get feedback from #general rather than just this WG.

**Comment by lenucksi** [comment]
> 
> 
> > Note from last meeting: Klaas volunteered to drive this task, but he isn't part of this github project yet, so we cannot assign the issue to him.
> 
> Just reached out to @kjs via mail to remind him to accept the GitHub invite. Once he accepts, we can put him on the ticket and mention him easier.

I successfully invited Klaas to the org now. He's @user-group.

**Comment by spier** [comment]
Really, @user-group? Well that is an epic user name for sure :)

**Comment by spier** [comment]
We will wait for Klaas to be back after the summit.

**Comment by claredillon** [comment]
Tapajit dey now leading this. Please review the draft survey and comment in the #survey slack channel

**Comment by claredillon** [comment]
Held call on survey plans. Tapajit updating the draft survey as a result of feedback. Proposed the idea of "champions" in orgs doing InnerSource, who can help get us minimum responses from that org. More details shortly.

**Comment by dicortazar** [comment]
There are currently 25 entries. We're willing to reach to 50.

Some actions:
* Provide a template (LinkedIn and Twitter) to share this survey
* Survey is currently running. We'll ask the board to retweet and re-share in LinkedIn.
* Ask previous speakers to share the survey and fill the survey if possible.

**Comment by claredillon** [comment]
Completed in 2020 by Tapajit Dey. Details here: https://tapjdey.github.io/InnerSource_Survey_2020/index.html
