### ISSUE TITLE
Create a Press Releases page

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#111]
Considering the fact that we are going to have a few big announcements coming it would be good to keep them documented on a Press Releases page on the website. 

This is going to help keep track of the history of InnerSource Commons as well as provide a place that we can link back to in our social promotions.

I suggest the Press Release page be similar to the Learning Path page in structure, without a featured article. 

The Press Releases page should sit under within About menu item

**Comment by clcoffey** [comment]
The first press release for ISC incorporation can be found here: https://docs.google.com/document/d/1d7FJKWMVwAjt4jwget5_wWNmcmtq45viaK1jBtq6AjU/edit?usp=sharing 

Image for the press release:
![Incorporation of ISC Foundation 1](https://user-images.githubusercontent.com/78749459/132473888-95172f6d-f9a6-4d64-8b43-a870b8157e99.png)

**Comment by voborgus** [comment]
Hi! Do we have a long-term plan of updates in this section? If no, there is the risk to have a useless page with old materials as we had on the previous site after some time.

**Comment by clcoffey** [comment]
With the sponsorship programme up and running we will have Press Releases more regular now. 

We have counted 5 press releases coming up in the next couple of months already

**Comment by claredillon** [comment]
Discussed this earlier with Cristina - some notes from that:
- We will call this "announcements" not press releases to give us flexibility.
- With the new sponsorship program, we will doing new announcements _at least_ every 6 months (e.g. "Our new supporters are....")
- we intend to also include announcements about new members
- We need it too as a reference point for co-promotions with our new partners (PR departments looking for web page links to reference). 
- So - there will be regular content, and less of a risk of it turning into a stale old page as before (when there was no marketing WG)
