### ISSUE TITLE
Upload the Summit 21 videos to YouTube

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#127]
Completing this issue requires access to InnerSource Commons YouTube account and Google Drive folders.

For each video:
-	Start with the headshot JPG for 3 sec.
-	Cross fade into Sponsor slide for 2 sec.
-	Cross fade into the session video.
-  Store in the "Session Recordings - YouTube folder on GDrive.

For the start of the Playlists:
-	Create a video of the “welcome- part1” jpg for 3 seconds (jpgs in headshot folder)
-	Include the video of the “welcome – Part1” at the start of the part 1 playlist
-	Repeat for Part 2 & 3
-	Use the generic Welcome slide for the 4th full playlist of all the parts. 

For YouTube:
-	Upload Part 1 videos first.
-	Create Part 1 playlist.
-	Then Part 2 and Part 3 in turn.
-	At the end create a 4th playlist for all the summits.

For each video uploaded, please include in the description:
o	Session Abstract
o	Speaker bio
o	You’ll find all of those on the event page.
o	Hashtags: InnerSource and InnerSourceSummit

Status:

Videos Ready
- [x] Chair's Address - Danese Cooper (InnerSource Commons) 
- [x] President's Address - Isabel Drost-Fromm (InnerSource Commons) 
- [x] Keynote: Brian Behlendorf in conversation with Danese Cooper
- [x] Gil Yehuda (US Bank) - InnerSource and Corporate Culture
- [x] Daniel Izquierdo & Igor Zubiaurre (Bitergia) - Working on an InnerSource Organizational Model
- [x] Olivia Buzek (IBM) - Birth of InnerSource at IBM
- [x] Zack Koppert (GitHub) - InnerSource in Government: Trust & Vulnerability
- [x] Russ Rutledge (WellSky) - Wide-Scaled InnerSource with a Core Team
- [x] ISC Lookback - Georg Grutter (InnerSource Commons) 
- [x] Matt Cobby (National Australia Bank) - InnerSource at NAB
- [x] An Xu (DiDi) - Cultivating InnerSource Community by Adapting to the Paradigm of Open Source Community Development
- [x] Ankit Pandey (Wipro) - The Role of HR policies in a Successful InnerSource Program
- [x] David Terol (Philips) - InnerSource at Scale - Fail Fast
- [x] Dirk Riehle (FAU) - An Introduction to InnerSource & Transfer Pricing
- [x] Ana Jimenez Santamaria (LF / TODO Group) - Building Bridges Betweem ISPOs & OSPOs
- [x] Jerry Tan (OpenAtom.org) - InnerSource & DevOps
- [x] Mishari Muqbil (Zymple) - Piggybacking InnerSource on to Agile and DevOps
- [x] ISC Looking Forward / Plans for the Future - Clare Dillon (InnerSource Commons)
- [x] Keynote: Jono Bacon - The Battle For Innersource Buy-In
- [x] Joe Patrao (Bloomberg) - InnerSource Metrics, Value & ROI
- [x] Jesús Alonso Gutiérrez (Santander) & Daniel Izquierdo (Bitergia) - Barriers to Contribute in a More Collaborative & Transparent Way
- [x] Sherin Mirza (Shell) - InnerSource - the Glue Between DevOps teams in a High-performing Organization
- [x] Wayne Haber (GitLab) - Open Practices in GitLab
- [x] Arno Mihm (Microsoft) - InnerSource at Microsoft
- [x] Elspeth Minty (Morgan Stanley) - Moving a Legacy Codebase to an InnerSource Model

Playlists:

- [x] Part1 Playlist Ready to Publish
- [x] Part 2 Playlist Ready to Publish
- [x] Part 3 Playlist Ready to Publish
- [x] Full Summit Playlist Ready to Publish

- [x] Part1 Playlist Published
- [x] Part 2 Playlist Published
- [x] Part 3 Playlist Published
- [x] Full Summit Published

**Comment by clcoffey** [comment]
Everything is now ready to publish

**Comment by claredillon** [comment]
Thanks @clcoffey and @Katiegilroyy for the work in getting these done!!
