### ISSUE TITLE
Decide 2022 Schedule

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#131]
Decide the schedule for Marketing WG Meetings for 2022.

Also decide the schedule for Community Calls (so they don't clash). 

Background:

At the last Marketing WG Meeting (Dec 7th) - it was proposed to pause WG meetings until after the holidays.

After a follow-up with @clcoffey, we propose the following schedule for 2022. This is a thread to capture feedback and agree final decision.

Our starting thoughts/reasonings:
- Want to accommodate those folks who take longer holiday breaks over Xmas.
- Want to leave sufficient time between Marketing Meetings and Community Calls (to allow for promotion)
- Discussed experimenting with having Marketing Meetings the same week at different times. This will allow for the same topics to be further developed/discussed by the APAC community in the same week as for the EU/US audience.
- Community Calls should not be on the same week (as some people go to both).
- Moving community calls to end of month, so we can promote via newsletter earlier in month.

**Comment by claredillon** [comment]
Proposal for **Marketing Working Group Meetings 2022.**

US/EU
- Starting Tuesday, 11th January.
- Time: 4pm UTC
- Ever 2 weeks after that.


EU / APAC
- Starting Thursday, 13th January
- Time 9am UTC
- Every 2 weeks after that.


Proposal for **Community Calls 2022**

US/EU

Starting Tuesday, 18th January
Time: 5pm UTC
EU/APAC

Starting Wednesday, 26th January
Time 9am UTC
Repeat dates TBD

**Comment by claredillon** [comment]
Proposal for Community Calls 2022

US/EU
- Starting Tuesday, 18th January
- Time: 5pm UTC

EU/APAC
- Starting Wednesday, 26th January
- Time 9am UTC

Repeat dates TBD

**Comment by shurrey** [comment]
This schedule works for me

**Comment by claredillon** [comment]
Proposal in today's marketing meeting to switch the WG meeting at this time (4pm-5pm UTC) to Wednesday (so we don't clash with the community calls, a constant challenge in 2021). Any thoughts on that?

**Comment by clcoffey** [comment]
I think it's a great idea. It's also closer to the APAC meeting which is good.

**Comment by claredillon** [comment]
We trialed Wednesday this week for EMEA/US meeting, and it didn't work well:

-Confusion with the reminders / crying for APAC the following day
- Some of our "regulars" have regular clashes
- Noted it also clashes with other meetings from FINOS/TODO which folks attend.

Decision made to move back to Tuesday. 

Also - in a related issue - we decided to move calls to Jitsi so we would have one link for all the Marketing Group calls to avoid future confusion (ongoing issues with rogue / legacy Zoom links appearing in calendars...)
