### ISSUE TITLE
Point innersourcecommons.net domain to the current site

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#137]
At the moment the .net version of the InnerSource Commons website is pointing to the old website. This is confusing as a lot of people manage to find it or land on it and believe they are looking at the current InnerSource Commons website. 

We want to keep that website as an Archive as it contains a lot of valuable information however we want the domain to point to innersourcecommons.org

I started this issue to discuss the best way forward and to agree on the next steps.

**Comment by rrrutledge** [comment]
Sounds like this hasn’t come up for a while.
