### ISSUE TITLE
Create Jitsi account for Marketing WG calls

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#138]
We've been having some ongoing issues with using Zoom for the WG calls - with some legacy links in calendar invites causing confusion. It has been suggested we get one Jitsi link as the Learning Path does for all the Marketing WG calls to avoid future confusion. Action is to do this for next EU/US WG Call (and add to all future calls).

**Comment by mishari** [comment]
Excellent choice

**Comment by claredillon** [comment]
Yes indeed - we tested this yesterday and it also allows for someone other than the organizer to start the call. So we have one link now for all future Marketing WG calls: https://meet.jit.si/ISCMarketing

Big thanks to @clcoffey for sorting this one!! :)
