### ISSUE TITLE
Confirm speakers for Feb 22 EU/US Community Call

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#139]
Aiming to have it on the theme of Security (as per the discussion on hot topics)

**Comment by claredillon** [comment]
Conley Rogers from GitLab confirmed. Seeking second speaker and host. Requests out. Volunteers welcome :)

**Comment by claredillon** [comment]
Date confirmed: Tue,  Feb 22nd 5pm UTC

**Comment by claredillon** [comment]
Three speakers confirmed:
- Vishal Kulshrestha (Verizon) & Conley Rogers (GitLab, ex Verizon) for first 10 min
- Elspeth Minty (Morgan Stanley) for second 10 mins.

Still need to confirm host.

**Comment by DavidPHirsch** [comment]
would be up for it, just want to better know what I have to do
