### ISSUE TITLE
Communications Strategy - Document current state

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#14]
Define ISC comms strategy, including outling all our channels and how we use each. This should include whether we have a newsletter and/or blog and strategy for both, if appropriate.

**Comment by claredillon** [comment]
Comms Strategy doc stored here to allow for input from Working Group: https://docs.google.com/document/d/1EaJVI7qcvU_B2nND7PJklEEdopRFU-SC_MlsosTHPRg/edit?usp=sharing

**Comment by spier** [comment]
@claredillon I read the doc and reformatted it a bit to make it easier to read the table.

Thanks for putting this together! The outlines of the different communication channels seems useful.

My main question is:
How do we now get from a list of channels to the communication strategy? What does that need to entail?
I haven't done this before, so I have honestly no clue :)

**Comment by claredillon** [comment]
Good questions @spier (and thanks for the changes made) - as per conversations on how we can be more productive, I propose we consider this initial task complete, in that it has outlined current status. We can address each element as we decide to invest in it further and update this doc as we do. Changed title to reflect this.

**Comment by spier** [comment]
I updated the linked document, so that that doc also mentions that it does not describe the Communication Strategy, but rather status current status.
