### ISSUE TITLE
Bugs on the InnerSource in Action page

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#149]
- [x] The citation text for Walmart and WayFair is the same (likely a bug) - raised by @spier 
- [x] The citation fo GitHub sounds strange to me: "The reason why InnerSource works is because like open source you're working with people who are collaborating with different priorities kind of thing because they're working on different things".
From "kind of thing ..." onwards I don't understand what it means anymore - raised by @spier 
- [x] Bosch - can't find the reference to the company in the article (same link as Bloomberg)
- [x] Elbit Systems link is broken
- [x] Engie points to this article but I can't find them on the page: https://resources.github.com/whitepapers/introduction-to-innersource/
- [x] Entelgy points to ISC Fall 2018 but I can't find them mentioned on the page
- [x] Ericsson link is broken
- [x] Europace link is broken
- [x] Harvard Business Review Link is broken
- [x] IAG points to an article about Globant. I couldn't find a mention of IAG in that article 
- [x] we haven't included Globant on the list.
- [x] Wiley is in the wrong place alphabetically.
- [x] Nasa Link is the same as Red Monk and I can't find Nasa mentioned in that article at all.
- [x] Nokia Bell Labs, link is broken too
- [x] Shutterstock link is to the Spring Summit 2019 but I can't find them on the agenda
- [x] The Hartford also has the Tencent video link.
- [x] Tencent link is the same as Twilio
- [x] Zendesk Link is the same as the Wipro link.
- [x] Zalando article on the InnerSource in Action page is broken should be changed to https://opensource.zalando.com/docs/resources/innersource-howto/

**Comment by spier** [comment]
Wow, that's a lot of bugs!
Great eye @clcoffey but not so good that we had so many bugs on that page :(
