### ISSUE TITLE
Setup monthly reporting to LP WG

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#15]

**Comment by claredillon** [comment]
@rrrutledge  has added an agenda item for Marketing update to the first Learning Path WG meeting of each month.

**Comment by rrrutledge** [comment]
Yes!  Please come by to the first meeting of each month.  You can see this item in the [agenda template](https://docs.google.com/document/d/16pTjdrihudETbt-WSzgRSJgkIL0xm8wLKMKsvRoEGxs/edit?usp=sharing).

**Comment by spier** [comment]
@claredillon This issue is in Done, but not closed. Can it be closed?
