### ISSUE TITLE
March Newsletter

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#153]
In preparation for the March Newsletter, please use this space to highlight things you would like to be included. These can be:
- Pattern of the month
- Learning Path updates
- Favorite InnerSource articles, videos or resources you have come across over the past month. 

The deadline for submission is the End of the day Thursday (March, 3rd)

**Comment by rrrutledge** [comment]
Did you know that [the Learning Path](https://innersourcecommons.org/learn/learning-path/) has been translated into 7 languages?  Check out [the website](https://innersourcecommons.org/learn/learning-path/) to see if the translation is finished into your language of choice!  We currently have active efforts to finish the German and Spanish translations, so join us in the [#learning-path](https://app.slack.com/client/T04PXKRM0/CARTU4XV2) channel if you can lend a hand!

**Comment by spier** [comment]
For the patterns part of the newsletter:




In an org with multiple legal entities, sometimes legal concerns can hinder InnerSource adoption.

For example when two legal entities within an organization want to share code with each other, they may need an agreement about the terms and often a legal contract. Creating such agreements on a per-project basis takes effort and may become a barrier for sharing.

An [InnerSource License](https://patterns.innersourcecommons.org/p/innersource-license) can help. It provides a reusable legal framework for the sharing of source code within the organization. This opens up new collaboration options, and makes the rights and obligations of the involved legal entities explicit.

For even more InnerSource patterns see:
[patterns.innersourcecommons.org](https://patterns.innersourcecommons.org)

**Comment by clcoffey** [comment]
@rrrutledge and @spier Thank you for your contribution to this month's Newsletter! I just sent it out so I hope you are enjoying the read. I will close this issue now and open it again next month.

**Comment by rrrutledge** [comment]
I see it!  Thank you!
