### ISSUE TITLE
GDPR Compliance / Imprint / Privacy Policy

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#16]

**Comment by lenucksi** [comment]
How does that relate to #9 and can we merge them?

**Comment by spier** [comment]
@claredillon can you clarify if this is is a duplicate of issue #9? 

"Imprint / Privacy Policy" sound like they might be different tasks than just GDPR but it would be great if you could clarify this.

**Comment by claredillon** [comment]
Closing issue as a duplicate of #9
