### ISSUE TITLE
April Newsletter

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#166]
In preparation for the April Newsletter, please use this space to highlight things you would like to be included. These can be:

- Pattern of the month
- Learning Path updates
- Favorite InnerSource articles, videos or resources you have come across over the past month.

The deadline for submission is the End of the day Thursday (April, 7th)

**Comment by clcoffey** [comment]
State of InnerSource report

**Comment by spier** [comment]
Sorry that I didn't have time to help here.

Looks like you picked the [Crossing the chasm](https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/368/files) PR? Thanks!

Also I suspect this issue can be closed, so I am just doing that.
