### ISSUE TITLE
Website Visitor Tracking / Analytics

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#17]
Get some basic info on how many people visit the ISC website, which pages most popular etc. @mishari volunteered to look at this in WG meeting of 17/08/2020

**Comment by lenucksi** [comment]
We need to get the Google Search Console going and for that we ideally should use DNS validation for which we'll need @cewilliams to do a few DNS changes.

Here's what the Google Search Console will bring us: https://search.google.com/search-console
This is the first step of SEO, works for Yandex and Bing too. All need DNS changes to validate the access.

**Comment by lenucksi** [comment]
If we would have an option to use self-hosted, privacy-friendly Matomo this would be nice, but since we don't have custom hosting, we'll likely fall back to Google Analytics I think?

**Comment by mishari** [comment]
After looking around I think we should try Clicky https://clicky.com which I've used on one of my sites. Their free plan allows for 3,000 page views per day.

https://clicky.com/help/pricing

**Comment by lenucksi** [comment]
> After looking around I think we should try Clicky https://clicky.com which I've used on one of my sites. Their free plan allows for 3,000 page views per day.
> 
> https://clicky.com/help/pricing

Reads interesting. Do they do API integration with search engine terms using the Google search console API?
Also, the moment we integrate this we need a custom privacy policy and full cookie compliance. (There's Cookie Compliance 3rd party vendors, some are free for one website)

**Comment by spier** [comment]
@mishari I was wondering if you would like any help on this task?

**Comment by mishari** [comment]
@spier apologies, I need to get back to this end of November as I'm in the middle of a project. Anyone who would like to take over is most welcome to.

**Comment by spier** [comment]
hey @mishari. no problem at all, totally understandable as these are all volunteered hours towards the project :)

Do you have an intermediate state already that you could hand over in case anybody wants to continue in them meantime?

Or is the current status basically the research above i.e.
- use clicky.com or Google Analytics
- figure out which privacy policy and cookie compliance we need once we use that tool

**Comment by claredillon** [comment]
@voborgus activated Google Analytics on the new website (Mar 2021). Closing this issue.

**Comment by lenucksi** [comment]
Don't forgot to update the privacy police, add a cookie notice system, data processing agreement and all the other things that come with Google Analytics and are required due to being active within the European market and hence subject to GDPR.
