### ISSUE TITLE
June Newsletter

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#176]
In preparation for the June Newsletter, please use this space to highlight things you would like to be included. These can be:

- Pattern of the month
- Learning Path updates
- Favorite InnerSource articles, videos or resources you have come across over the past month.

The deadline for submission is the End of the day Friday (May, 27th)

**Comment by spier** [comment]
As "Pattern of the month" please use:
https://patterns.innersourcecommons.org/p/30-day-warranty

Thank you!

**Comment by clcoffey** [comment]
New Supporter
New Services Directory

**Comment by clcoffey** [comment]
Discussion about Thailand Meetup: https://github.com/InnerSourceCommons/InnerSourceMarketing/discussions/177
