### ISSUE TITLE
September Newsletter

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#180]
In preparation for the September Newsletter, please use this space to highlight things you would like to be included. These can be:

- Pattern of the month
- Learning Path updates
- Favorite InnerSource articles, videos or resources you have come across over the past month.

The deadline for submission is the End of the day Tuesday (Aug, 30th)

**Comment by claredillon** [comment]
Be great to include the recordings from a FINOS interview over the summer - thanks Cristina! :)
https://resources.finos.org/znglist/industry-discussion-inner-source-and-open-source-sigs/?c=cG9zdDo5OTA2Njk=

**Comment by clcoffey** [comment]
@kschueths suggested this article in slack. 
https://medium.com/promyze/innersource-understand-the-benefits-in-5-minutes-8a07367228bf

**Comment by CiaraFlanagan** [comment]
Hey everyone
September's Pattern of the Month is the 'Common Requirements' pattern: https://patterns.innersourcecommons.org/p/common-requirements

We want to celebrate the learning from this pattern in our monthly update for members and on LinkedIn and Twitter.

Here's the link to the draft content:  

https://docs.google.com/document/d/1K3b3pXJ13TWWwWyvpQq6LpbBPVIK2mbOKZpSM5ZIen0/edit?usp=sharing

Your feedback on length, style, key messages - ANYTHING - is very, very welcome.  Comments and/or suggested edits  are needed by 9am BST, Friday 2nd September.

A huge thanks to the InnerSource members who made this pattern happen.
