### ISSUE TITLE
October Newsletter

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#181]
In preparation for the October Newsletter, please use this space to highlight things you would like to be included. These can be:

- Pattern of the month
- Learning Path updates
- Favorite InnerSource articles, videos or resources you have come across over the past month.

The deadline for submission is the End of the day Friday (Sep, 30th)

**Comment by CiaraFlanagan** [comment]
Hi there Cristina

I'm proposing 'Standard Base Documentation' for the 'Pattern of the Month'.

https://docs.google.com/document/d/1TZCX6kH7eSJpBGnxcfSjy2Qi7oyKrqp-DKclwHKA02M/edit?usp=sharing

The visuals are from the pattern.

**Comment by anajsana** [comment]
Small feedback that might help in the future: Something that worked in TODO community was to create a [newsletter template](https://github.com/todogroup/ospology/blob/main/newsletter/newsletter-template.md) and [markdown files for each issue](https://github.com/todogroup/ospology/tree/main/newsletter) so the community can add their suggestions directly as PR. The day of the publication, everything is mirrored to the OSPO newsletter platform ➡️ https://www.getrevue.co/profile/osponews

**Comment by spier** [comment]
@clcoffey when is this newsletter going out? I might try to produce an updated version of the visual for the 'Standard Base Documentation' pattern, which we can then use both in the newsletter and the pattern itself.

**Comment by clcoffey** [comment]
We are aiming for early next week.

**Comment by spier** [comment]
Ok, I might be able to make that.

**Comment by spier** [comment]
@CiaraFlanagan I created new visuals for this pattern, see:
https://patterns.innersourcecommons.org/p/base-documentation

Could you integrate those into the newsletter?

**Comment by clcoffey** [comment]
Will do

**Comment by CiaraFlanagan** [comment]
> Small feedback that might help in the future: Something that worked in TODO community was to create a [newsletter template](https://github.com/todogroup/ospology/blob/main/newsletter/newsletter-template.md) and [markdown files for each issue](https://github.com/todogroup/ospology/tree/main/newsletter) so the community can add their suggestions directly as PR. The day of the publication, everything is mirrored to the OSPO newsletter platform ➡️ https://www.getrevue.co/profile/osponews

**Comment by CiaraFlanagan** [comment]
Hi @anajsana 

I'm going to start working on the Newsletter in the next month or so and I'm really interested in the TODO process for creating the newsletter. 

Would you have time for a very quick chat zoom chat about it next week?  

I'm free Tuesday - Friday mornings until 1.30pm (Irish time) or we could try and find a later time that worked for you, if you would prefer?
