### ISSUE TITLE
November Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#184]
In preparation for the November Newsletter, please use this space to highlight things you would like to be included. These can be:

- Pattern of the month (I'm proposing the InnerSource Portal pattern - have a look at the link below)
- Learning Path updates
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- News about your InnerSource project!

The deadline for submission is the end of the day Monday 24th October.

**Comment by CiaraFlanagan** [comment]
Social media content for the InnerSource Portal Pattern - November's Pattern of the Month:
 
https://docs.google.com/document/d/119U-GOIa6JVTIn8E6GmQwDmxB-LNputruFHzLcwhLus/edit?usp=sharing

**Comment by rrrutledge** [comment]
The **Trusted Committer** section of the Learning Path is now [available in French](https://innersourcecommons.org/fr/learn/learning-path/trusted-committer/)!  Check it out, and join us to [contribute to future translations](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/main/CONTRIBUTING.md#translations) and #learning-path content.

**Comment by nearlythere** [comment]
I just learned about Innersource Commons by seeing Clare Dillon at NI Developer Conference in Belfast. Maybe newsworthy to highlight this outreach? It's gained at least one new fan (me!) and hopefully more. Love to see folks coming up to Belfast. 

Suggest under "Favorite resources" 

>📣 Clare Dillon spoke at NI Developer Conference in Belfast "Breaking down silos with InnerSource," Saturday, 22 October 2022. Video https://www.youtube.com/watch?v=hvtZnbDXpzM

**Comment by clcoffey** [comment]
https://www.harihareswara.net/posts/2022/reluctance-to-process-contributions-and-tips-from-innersource/

**Comment by clcoffey** [comment]
https://resources.finos.org/znglist/industry-discussion-innersource-and-open-source-sigs/?c=cG9zdDo5OTA2Njk%3D&utm_campaign=Interviews&utm_content=224446045&utm_medium=social&utm_source=twitter&hss_channel=tw-4858563561

**Comment by clcoffey** [comment]
https://github.com/readme/guides/github-enterprise-kpmg

**Comment by clcoffey** [comment]
Open Source and InnerSource Skills in Ireland: A Call for Action report.
https://www.openirelandnetwork.com/report/
