### ISSUE TITLE
February Newsletter - 2023

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#187]
We are preparing content for our February Newsletter.

Please use this space to highlight things you would like to be included. These can be:

- News about your InnerSource project!
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month 
- Any members that you wish to recognise for their great work 

The **deadline** for submission is the end of the day **Friday 27th January**.

**Comment by spier** [comment]
### Patterns in Chinese

An amazing group of people put in a lot of work to translate the most mature InnerSource patterns to Chinese :cn: !
Find them at [patterns.innersourcecommons.org/v/zh/](http://patterns.innersourcecommons.org/v/zh/)

Thank you so much Willem Jiang, Wenxuan Long, Zhenhua Sun, Yong Chen, Jerry Tan, and Xu An.

**Comment by mishari** [comment]
FOSSASIA is hosting an InnerSource track in Singapore on April 13th-15th. Attendees can register at https://summit.fossasia.org/. The deadline for speaker submissions is February 8th, and all Inner/Open Source related topics are welcome. https://eventyay.com/e/7cfe0771/cfs

**Comment by CiaraFlanagan** [comment]
what we're listening to:

https://www.thelabviewexperiment.com/episodes/episode-1-creating-a-better-developer-experience-pbsjf-br4eg-9yg2f-pmakf-292rp-ewm54-af5k8-k6r65

**Comment by CiaraFlanagan** [comment]
https://dzone.com/articles/inner-source?utm_campaign=innersource-efficiency-and-quality-of-open-source-in-the-corporate-world&utm_medium=social_link&utm_source=missinglettr-twitter

**Comment by claredillon** [comment]
What we're reading: Not sure if this one was done before (published in Dec 22) - just saw it in a tweet: https://dzone.com/articles/inner-source?utm_campaign=innersource-efficiency-and-quality-of-open-source-in-the-corporate-world&utm_medium=social_link&utm_source=missinglettr-twitter

**Comment by CiaraFlanagan** [comment]
Add news about translation - Thomas Froment

**Comment by CiaraFlanagan** [comment]
https://github.blog/2021-03-23-solving-the-innersource-discovery-problem/

**Comment by spier** [comment]
> https://github.blog/2021-03-23-solving-the-innersource-discovery-problem/

@CiaraFlanagan haven't we shared that link in the newsletter already? It is from 2021.

**Comment by claredillon** [comment]
For the record, when we started the "what we're reading" section in the newsletter we did discuss whether it was just newly published things - and some feedback was that we might be talking in Slack or online about something that was published a long time ago - and it's relevant to highlight it again (maybe because of context changes etc.). 

Perhaps we need to flag older content to give that context somehow... like "here is an oldie but a goodie..." (does that Irish phrase translate??)

**Comment by spier** [comment]
Sure, if that is the approach, that is completely fine too.

**Comment by CiaraFlanagan** [comment]
Note a blogpost/article about recent Community Call on ISPO working group

**Comment by CiaraFlanagan** [comment]
https://www.bbvaaifactory.com/mercury-acelerando-la-reutilizacion-en-ciencia-de-datos-dentro-de-bbva/

**Comment by CiaraFlanagan** [comment]
> 

@mishari 

I saw your slack message today that FOSSASIA are still looking for InnerSource speakers so I've focused on this (more than open source) in the newsletter.  I hope that's ok.

**Comment by CiaraFlanagan** [comment]
Newsletter ready to publish. Waiting on some minor clarifications from community members.
