### ISSUE TITLE
Publish our past newsletters.

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#188]

**Comment by claredillon** [comment]
Here is the link to all our newsletters: https://us1.campaign-archive.com/home/?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2

I am not sure where is the best place to put this on the website. So noting here in case someone would like to propose something.

**Comment by claredillon** [comment]
This came up as a suggestion in Slack.

**Comment by CiaraFlanagan** [comment]
As we don't have a dedicated resources page, I'm wondering if we should add a link to previous newsletters to:  https://innersourcecommons.org/community/

We could see what it looks like directly underneath or above our twitter feed.

Unfortunately, I'm not up to speed with making this type of change to the website so I'm not able to test it out.

**Comment by spier** [comment]
We could put some text and a link below the "Sign up to our mailing list" box?

i.e. like this:

![Screenshot 2023-01-28 at 22 00 47 ](https://user-images.githubusercontent.com/163029/215290982-dac51412-ddf9-40a6-94a1-b322d819cb1d.png)

We could also add a newsletter icon next to the existing social media icons at the bottom right?
While a newsletter isn't exactly social media, our mailchimp archive is another place where you can find ISC content, outside of innersourcecommons.org

**Comment by CiaraFlanagan** [comment]
I like it, Sebastian

I'm assuming the 'Read previous newsletters' button brings us to this link:  

https://us1.campaign-archive.com/home/?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2

**Comment by rrrutledge** [comment]
This seems like a pretty easy to add to the newsletter - @CiaraFlanagan ?

**Comment by rrrutledge** [comment]
@andrea-kyurchiev can you put this on the website?
