### ISSUE TITLE
Get feedback from the ISC board on metric goals

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#19]

**Comment by claredillon** [comment]
Danese is working with the ISC board/Members to get input on overall goals for the Marketing & Outreach Working Group - this will feed into the metric discussion and the Communications Strategy.

**Comment by lenucksi** [comment]
@danese will do something about this.

**Comment by lenucksi** [comment]
Board says: 
- Look at current numbers
- Come up with suggestions for numbers that we want to achieve, maybe until the end of the year and have them accepted by the board
- Acceptance: We've created this proposal and put it here.

We already have this here, made by @claredillon: https://github.com/InnerSourceCommons/marketing-wg/blob/master/metrics.md

**Comment by lenucksi** [comment]
#13 and #9 are strongly related.

**Comment by spier** [comment]
@claredillon in the meeting today it sounded like you would create a first proposal for metrics and targets/goals for those metrics?

I would be happy to give you feedback on the proposal from a "newbie" perspective, as that would allow me to review the existing documents related to this that were created by this working group before.

**Comment by claredillon** [comment]
Feedback was that the Marketing WG should come up with proposed targets and let ISC board know. Closing this issue as there is a separate issue already there for defining metrics and targets.

**Comment by lenucksi** [comment]
> Feedback was that the Marketing WG should come up with proposed targets and let ISC board know. Closing this issue as there is a separate issue already there for defining metrics and targets.

Suggestion: If there is a separate issue it would be fabulous to just put in the issue number here, e.g. "separate issue (#4711)" so interested people can effortlessly click-through to the new one.
