### ISSUE TITLE
Add [Komyu] logo to the Stories Page

### ISSUE THREAD

**Issue by tfroment** [InnerSourceCommons/InnerSourceMarketing#190]
### Issue Checklist

_Note:_ This is done by the person that wants to add their org logo to the website.

- [X] Replace `[organisation name]` with your company name in the title of this GitHub issues.
- [X] Check the [Stories Page][stories] on the website to see if the logo of your organisation is already featured
- [X] Upload the logo of your organisation to this issue. Nname the logo according to the template `organisation_name.png`.
![organisation_komyu](https://user-images.githubusercontent.com/62097390/213859023-39497b2e-850c-4c3b-a29d-594b91c1b189.png)
- [X] Provide a link to evidence of the company doing InnerSource (this could be an article, a video, or a [pattern][patterns-repo]
    - https://www.linkedin.com/company/komyuclub/
    - https://www.youtube.com/watch?v=aCbv46TfanA (talk from co-founder in 2020)
    - https://innersourcecommons.org/fr/events/isc-spring-2019/ (talk from co-founder in 2019) 
    - https://incose.onlinelibrary.wiley.com/doi/abs/10.1002/inst.12325 (Research article from co-founder)
    
### Steps to add the logo to the website

_Note:_ This is typically done by a website administartors (or by you, if you are familiar with git/GitHub).

- [x] fork the [website repository][website-repo]
- [x] add the logo file to the folder `static/images/logos`, following this template for naming the logo file: `organisation_name.png`
- [x] edit the file for Stories Page located at: `content/en/stories/_index.md`
- [x] add the logo in the correct place in the list, following alphabetical order. Include the link to the evidence, by using the following code snippet. If the evidence is an article, replace 'video' with 'article'.
```
{{< company name="[Company Name]" image="/images/logos/[organisation_name].png" video="[link to evidence]">}}
{{< /company >}}
```
- [x] if you want to provide an extra quote about how your org is applying InnerSource, extend the entry like this:
```
{{< company name="[Company Name]" image="/images/logos/[organisation_name].png" video="[link to evidence]" author_name="[author name here]" author_title="[author title/role here]">}}
[quote here]
{{< /company >}}


```
- [x] create a Pull Request. Specify in the Pull Request why you are adding the logo to the site e.g.: "I work for the company and know they are doing InnerSource".

### Acceptance Criteria

- The logo file is named according to the convention: `organisation_name.png`
- The logo file has been uploaded to the correct folder
- The logo appears on the [Stories Page][stories] in the correct place based on alphabetical order

### Help Needed / Blockers

[stories]: https://innersourcecommons.org/stories/
[website-repo]: https://github.com/InnerSourceCommons/innersourcecommons.org
[patterns-repo]: https://github.com/InnerSourceCommons/InnerSourcePatterns

**Comment by tfroment** [comment]
I am familiar with Github, you may assign it to me :)

**Comment by claredillon** [comment]
Thanks you @tfroment - this is one of our first ever issues pro-actively created for the InnerSource in Action page. We really appreciate it! Looking forward to seeing more from the French community! :)

**Comment by tfroment** [comment]
Thanks a lot @claredillon! yes, the french local community is one the rise 😃

**Comment by claredillon** [comment]
Might I add - cool logo! :)

**Comment by rahermur** [comment]
Hi! @tfroment @claredillon  I recently shared this [article](https://www.bbvaaifactory.com/mercury-acelerando-la-reutilizacion-en-ciencia-de-datos-dentro-de-bbva/) with the community about how we are applying inner source at BBVA AI Factory. Is it ok if we open a Pull Request to be added to the Stories page? Thanks!

**Comment by tfroment** [comment]
Pull request submitted https://github.com/InnerSourceCommons/innersourcecommons.org/pull/482

**Comment by tfroment** [comment]
I think we can close this issue as we will add Komyu on the "Services" page and not in the "Stories" page as discussed in https://github.com/InnerSourceCommons/innersourcecommons.org/pull/482
