### ISSUE TITLE
March Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#194]
We are preparing content for our March Newsletter.

Please use this space to highlight things you would like to be included. These can be:

News about your InnerSource project!

- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Any members that you wish to recognize for their great work

The deadline for submission is the end of the day Friday 24th March.

**Comment by CiaraFlanagan** [comment]
Yesterday, the Japanese InnerSource community looked back at 2022 and kicked off 2023. Special congratulations and appreciation go to 
[@Mass Kaneko](https://innersourcecommons.slack.com/team/U03L486DV2R)
 and 
[@Shoma Kubo](https://innersourcecommons.slack.com/team/U03NCNS4B3P)
 who both made extremely valuable contributions in 2022. :tada:
Mass Kaneko is currently leading the community translation of “Understanding the InnerSource Checklist”. Shoma Kubo manages the community and makes sure that events are well organized and delivered smoothly.
[@Mass Kaneko](https://innersourcecommons.slack.com/team/U03L486DV2R)
 and 
[@Shoma Kubo](https://innersourcecommons.slack.com/team/U03NCNS4B3P)
 - thank you so much for your contributions to InnerSource Commons!
![2022 MVC](https://user-images.githubusercontent.com/101422261/216136799-897c8859-a58a-4b54-b344-3075f19d4040.jpg)

**Comment by CiaraFlanagan** [comment]
https://www.youtube.com/watch?v=MTVr00Wbkws

**Comment by CiaraFlanagan** [comment]
Suggesting 'Communication Tooling' pattern for Pattern of the Month: https://patterns.innersourcecommons.org/p/communication-tooling 

Open to other suggestions though

**Comment by CiaraFlanagan** [comment]
https://www.promyze.com/inner-source-motivations/

**Comment by CiaraFlanagan** [comment]
https://t.co/xxVSejSk7I

**Comment by CiaraFlanagan** [comment]
Add advertisement for ISPO WG:

https://innersourcecommons.org/community/

**Comment by claredillon** [comment]
[https://github.com/customer-stories/philips](https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcustomer-stories%2Fphilips&data=05%7C01%7C%7C62c82c62bc9849825d6208db10bc8178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638122174029046519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P5ZlfTZ%2FiiqBFbX0WU06nIakKzCazZAC5w1%2BHiKxIrQ%3D&reserved=0)

**Comment by cteyton** [comment]
https://reader.elsevier.com/reader/sd/pii/S0164121220300030?token=7792C57A208AE956B76D8A4A3135EEF66B4F2A062994CC021FA334A9F736FE91498D90CCB5A620A4EEE7598F69F2B17A&originRegion=eu-west-1&originCreation=20230217134457

**Comment by CiaraFlanagan** [comment]
InnerSource Gathering at FOSS BackStage (message saved on slack)

**Comment by CiaraFlanagan** [comment]
https://www.promyze.com/innersource-key-benefits/

**Comment by CiaraFlanagan** [comment]
https://github.blog/changelog/2023-02-16-more-love-for-innersource-collaboration-and-enterprise-fork-policies/

**Comment by CiaraFlanagan** [comment]
https://podcast.sustainoss.org/154

**Comment by rrrutledge** [comment]
The InnerSource Commons has a new working group!  The ISPO working group supports those that are working to scale InnerSource throughout their company.  Members of the working group collaborate to produce shared materials - tooling, training, and documentation - that are out in the open and available for anyone to use.  Rather than each company producing their own materials we collaborate and share them as open source projects so that we all get further ahead.  Join us in the [#ispo-working-group](https://app.slack.com/client/T04PXKRM0/C04DT6NQX7G/) channel in the InnerSource Commons _Slack_.

**Comment by CiaraFlanagan** [comment]
https://github.com/customer-stories/philips

**Comment by CiaraFlanagan** [comment]
https://medium.com/philips-technology-blog/how-philips-used-innersource-to-maintain-its-edge-in-innovation-38c481e6fa03

**Comment by pmalirz** [comment]
Hi, I know I'm late but maybe, jf possible, my blog post:
https://przemek.malirz.pl/blog/unlocking-the-power-of-inner-source/

**Comment by rrrutledge** [comment]
@pmalirz this is a great summary and showing of how the material in InnerSource patterns can come together to show how to benefit your organization.  What motivated you to write this wonderful piece?

**Comment by CiaraFlanagan** [comment]
https://www.linuxfoundation.org/research/improving-enterprise-os-dev?hsLang=en&utm_content=238388497&utm_medium=social&utm_source=twitter&hss_channel=tw-14706299

**Comment by CiaraFlanagan** [comment]
https://www.promyze.com/inner-source-motivations/

Credits to the paper "What Motivates Software Practitioners to Contribute to Inner Source? by Zhiyuan Wan et al., published in the ESEC/FSE 2022 conference"

**Comment by pmalirz** [comment]
> @pmalirz this is a great summary...

Thank you very much @rrrutledge! Well, I've been presenting those 3 ways in my company and always wanted to write an article about it. I'm happy to hear you like it.

**Comment by rrrutledge** [comment]
Yes!  If you’re working in spreading InnerSource in your company @pmalirz then you should check out the #ispo-working-group.
