### ISSUE TITLE
Mastodon account setup on fosstodon.org

### ISSUE THREAD

**Issue by dellagustin-sap** [InnerSourceCommons/InnerSourceMarketing#197]
### Purpose & Details

To be written - already discussd on Slack

### Acceptance Criteria

- [x] Logo and profile descriptions are setup
- [x] Profile metadata is setup (e.g. links)
- [x] Verification is added where possible
    - [x] innersourcecommons.org - https://github.com/InnerSourceCommons/innersourcecommons.org/pull/475
    - [x] GitHub Org - https://github.com/InnerSourceCommons/.github/issues/1
- [x] Featured hashtags
    - [x] `innersource`

### Help Needed / Blockers

N/A - At the moment I have all I need

### Links and references
- https://fosstodon.org/@innersource 
- https://docs.joinmastodon.org/user/profile/#verification

**Comment by dellagustin-sap** [comment]
Please assign this to me, it is in progress, I will use this issue to track progress and anything that is worth documenting during the process.

**Comment by claredillon** [comment]
Thank you so much @dellagustin-sap for helping us get masto-done! ;)

**Comment by dellagustin-sap** [comment]
_masto-done_, love it!

**Comment by claredillon** [comment]
mic drop and leaves

**Comment by dellagustin** [comment]
I'll not be able to immediately add the Mastodon icon to the social links in the website footer.
The themify icons (https://themify.me/themify-icons) do not include an icon for Mastodon.
I contacted them through their contact form, but I'm not expecting them to have this anytime soon.

**Comment by dellagustin** [comment]
Org link verification will be done with https://github.com/InnerSourceCommons/.github/issues/1.

**Comment by dellagustin** [comment]
Hello @claredillon ,

I have setup the profile.
The profile image is the same I downloaded from twitter.
I have written a bio that is rather neutral. Superlatives like _world's largest community_ are not very popular on the fediverse (at least from my point of view).
I have added as profile metadata the link to the website, the GitHub org and the Youtube channel (we can have up to 4). We could add LinkedIn or Twitter, but to be honest, the audience on the fediverse probably does not care about those.

The links can be showed as verified - for that I have the following issue and PR:
- https://github.com/InnerSourceCommons/.github/issues/1
- https://github.com/InnerSourceCommons/innersourcecommons.org/pull/475

Could you please take a look and see if there is any improvement needed?

If not, I'll later update the done criteria (I need to login from my other account for that), and this issue can be closed.

It is customary start by posting an introduction about yourself (in this case, about InnerSource Commons) using the hashtag `#intro`.

Also, we should promote on slack so that people start following us.

**Comment by spier** [comment]
@dellagustin great job setting up all the mastodon stuff. 

I handled both PR and issue linked above.

Is there is anything else that I can help with?

**Comment by dellagustin** [comment]
Thank you @spier, I think that is all for now.
I just entered in the profile edit mode and saved it again, now the website and github org both show as verified:
 
![image](https://user-images.githubusercontent.com/260113/218281938-1869f9d4-ef0a-4d8a-8e8f-fcd0e7177ab0.png)

**Comment by spier** [comment]
@dellagustin-sap looks like this whole thing is done, isn't it?

**Comment by dellagustin-sap** [comment]
@spier  I'm waiting for a review from @claredillon .

**Comment by claredillon** [comment]
Thanks @dellagustin-sap for this. Recommend a slight change to the wording.

InnerSource Commons is a community for those who practice InnerSource. We are dedicated to creating and sharing knowledge about #InnerSource, the use of open source practices within organizations. 

Reasoning:
- Publicly we always refer to InnerSource Commons as the community (and InnerSource Commons Foundation as the Foundation, when mentioning incorporation etc.). 
- Love the definition of InnerSource that you use (in fact loved it so much raised the suggestion it should be our official definition on the website with other Members) - however - there is some debate over the wording of the culture part right now ...so propose simplifying the text from the website for the moment.

**Comment by dellagustin-sap** [comment]
@claredillon , done.
About the definition, I took it from wikipedia: https://en.wikipedia.org/wiki/Inner_source

Just to make it handy for anyone else reading here: "InnerSource is the use of [open source](https://en.wikipedia.org/wiki/Open-source_software) [software development](https://en.wikipedia.org/wiki/Software_development) best practices and the establishment of an [open source-like culture](https://en.wikipedia.org/wiki/Open-source_model) within organizations[[1]](https://en.wikipedia.org/wiki/Inner_source#cite_note-1) for the development of its non-open-source and/or [proprietary software](https://en.wikipedia.org/wiki/Proprietary_software)."

In my previous usage, I left out on purpose the part "for the development of its non-open-source and/or [proprietary software](https://en.wikipedia.org/wiki/Proprietary_software).", as I don't like to restrict InnerSource and the open source culture to software development.

Anyway, from my perspective the setup is done, anything missing from your side?

**Comment by claredillon** [comment]
Thanks again @dellagustin-sap - next step is to decide how we use the Mastodon account. I think Ciara is planning to reach out to hopefully get some more tips on that. Our current plan is not to include Mastodon in our standard Social outreach until we know a little more about how to enable that and get to know the whole set-up better to figure out what works best.

**Comment by dellagustin-sap** [comment]
Hi @claredillon , I'll then close this issue, as the initial setup is complete. If I had ideas or info to share about the comms strategy for Mastodon, I'll take it to the marketing channel on Slack.
