### ISSUE TITLE
April Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#199]
We are preparing content for our April Newsletter.

Please use this space to highlight things you would like to be included. These can be:

News about your InnerSource project!

- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Any members that you wish to recognize for their great work

The deadline for submission is the end of the day **Monday, March 27**.

**Comment by CiaraFlanagan** [comment]
https://www.blip.pt/life-blip/posts/inner-source-implementation-in-flutter-tech/?utm_source=organic&utm_medium=twitter&utm_campaign=10.03.23_tweet

**Comment by CiaraFlanagan** [comment]
https://innersourcecommons.slack.com/archives/C04PXKRN4/p1678668953797819

Video link shared on general channel by Mishari

**Comment by kschueths** [comment]
https://www.linkedin.com/pulse/innersource-backstage-katie-schueths-mba

**Comment by CiaraFlanagan** [comment]
https://www.linkedin.com/company/cio-institute/

**Comment by CiaraFlanagan** [comment]
FOSS Asia - https://eventyay.com/e/7cfe0771

**Comment by CiaraFlanagan** [comment]
https://www.youtube.com/@InnerSourceCommonsJapan/videos

**Comment by CiaraFlanagan** [comment]
https://digitalisationworld.com/blogs/57365/innersource-ospos-and-a-move-toward-a-more-strategic-use-of-open-source

**Comment by CiaraFlanagan** [comment]
Yuki's new look youtube channel: https://www.youtube.com/@InnerSourceCommonsJapan/videos
