### ISSUE TITLE
**Cards**

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceMarketing#2]
Cards can be added to your board to track the progress of issues and pull requests. You can also add note cards, like this one!

That got converted

**Comment by lenucksi** [comment]
Let's mention some other repository / wg here https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/258

**Comment by rrrutledge** [comment]
👋

**Comment by lenucksi** [comment]
This thing is done and can be closed.
