### ISSUE TITLE
Decide on a Newsletter tool

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#20]
We have decided to publish a newsletter. Need to agree which tool to use that does the best job.

**Comment by lenucksi** [comment]
@danese has good experiences with MailChimp
@lenucksi suggests the trusty old mailing lists for double opt-in and "stuff just works"

**Comment by lenucksi** [comment]
This contains recommendations for tooling: https://docs.google.com/spreadsheets/d/1yd8ASzJvPEQ1l1BgQWtrFzJUwrfDdvMUN-xqltkfQnU/edit#gid=0

**Comment by spier** [comment]
Is anybody working on this issue right now? If not, I suggest we move it back to TODO.

**Comment by claredillon** [comment]
Mailchimp seems to be the most popular tool. Checked we can export data. Unless there are objection - propose we go for this, and use it to manage mailings for the Fall Summit too.

**Comment by claredillon** [comment]
Decision made on Mailchimp in Marketing meeting of 20th July 2020

**Comment by spier** [comment]
Is there any follow-up activity to this? 

e.g. Send the first newsletter via Mailchimp?
or
Setup Mailchimp to allow for more than 2 people to manage it.

Also are those follow-up activities run by the #summit-planning WG, or in #marketing ?
