### ISSUE TITLE
May Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#203]
We are preparing content for our May Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day Friday, April 28.

**Comment by CiaraFlanagan** [comment]
https://habr.com/ru/articles/730510/

**Comment by CiaraFlanagan** [comment]
https://opensource.com/article/22/12/markup-languages-documentation?sc_cid=7016000000127ECAAY

**Comment by rrrutledge** [comment]
https://resources.github.com/innersource/what-is-innersource/

**Comment by CiaraFlanagan** [comment]
https://docs.developer.tech.gov.sg/docs/innersource-in-the-government/

**Comment by CiaraFlanagan** [comment]
https://podcast.opensap.info/open-source-way/2023/04/26/debunking-innersource-myths/

**Comment by CiaraFlanagan** [comment]
https://podcast.opensap.info/open-source-way/2023/04/26/debunking-innersource-myths/

**Comment by CiaraFlanagan** [comment]
Thanks @rrrutledge for the article for the May newsletter.  Really appreciated that!
