### ISSUE TITLE
June Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#205]
We are preparing content for our June Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day **Friday, May 26**.

**Comment by CiaraFlanagan** [comment]
Add a call-out for moderators to newsletter

**Comment by rrrutledge** [comment]
Three ideas for things to put in, but they're not quite done yet.
* New Learning Path section: Project Leader.
* New Learning Path article: The InnerSource Mentality.
* New Learning Path translation: Brazilian Portuguese.

**Comment by chrisreddington** [comment]
Hi there! Please could we add [this blog post](https://github.blog/2023-05-08-building-a-culture-of-innovation-in-your-business-with-github/)? Thank you!

**Comment by CiaraFlanagan** [comment]
Check if this has been published before: https://github.com/customer-stories/mercedes-benz

**Comment by CiaraFlanagan** [comment]
Oldie but goodie: https://www.linkedin.com/pulse/culture-behaviors-innersource-three-part-blog-series-1-gil-yehuda/

**Comment by CiaraFlanagan** [comment]
Under talks and events: https://www.opensouthcode.org/conferences/opensouthcode2023/program/proposals/597

**Comment by CiaraFlanagan** [comment]
Event: https://www.finos.org/hosted-events/2022-06-21-finos-innersource-sig-panel-event?utm_campaign=2022-06-21%20Innersource%20SIG%20Panel%20Event&utm_content=211150147&utm_medium=social&utm_source=linkedin&hss_channel=lcp-18473937

**Comment by zkoppert** [comment]
article: https://github.com/customer-stories/vodafone

**Comment by rrrutledge** [comment]
New section of the InnerSource Learning Path - [The Project Leader](https://innersourcecommons.org/learn/learning-path/project-leader/).  Written material about the relationship of InnerSource to Agile, Open Source, capacity planning, and more!

**Comment by souravcipher** [comment]
Open Source Program Office (OSPO) Survey 2023 


https://www.research.net/r/SD6K27F

**Comment by CiaraFlanagan** [comment]
> Under talks and events: https://www.opensouthcode.org/conferences/opensouthcode2023/program/proposals/597

Newsletter published later
