### ISSUE TITLE
July Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#215]
We are preparing content for our June Newsletter.

Please share your suggestions for content. This can include:

News about your InnerSource project!
Any news about activities happening in the wider InnerSource community
Favorite InnerSource articles, videos or resources you have come across over the past month.
Learning Path updates
Pattern of the month
Our heroes of the month - any members that you wish to recognize for their great work
The deadline for submission is the end of the day Friday, June 30.

**Comment by CiaraFlanagan** [comment]
Article:  https://github.com/customer-stories/mercedes-benz

**Comment by CiaraFlanagan** [comment]
Article: https://medium.com/dynatrace-engineering/innersource-what-can-it-do-for-you-8610923144ab

**Comment by CiaraFlanagan** [comment]
https://apithedocs.org/podcast/innersource-and-meaning-collaboration-interview-daniel-izquierdo-and-kristof-van-tomme

**Comment by CiaraFlanagan** [comment]
Check and see relevance to InnerSource: https://www.youtube.com/watch?v=lwV3xRn2WyY

**Comment by rrrutledge** [comment]
There is a new segment of the Learning Path that is live - [The InnerSource Mentality](https://innersourcecommons.org/learn/learning-path/introduction/09/).  This segment shares a short and concise creed and commitment to InnerSource that is easy to understand and support and encourages all to adopt it.  Please have a look.  We hope that it's inspiring for you and useful for you to share with others in encouraging them to have a mentality for InnerSource.

**Comment by CiaraFlanagan** [comment]
Yuki - case study

**Comment by CiaraFlanagan** [comment]
Have I done this one before? https://resources.github.com/innersource/accelerate-2022/

**Comment by CiaraFlanagan** [comment]
new sponsors

**Comment by CiaraFlanagan** [comment]
> There is a new segment of the Learning Path that is live - [The InnerSource Mentality](https://innersourcecommons.org/learn/learning-path/introduction/09/). This segment shares a short and concise creed and commitment to InnerSource that is easy to understand and support and encourages all to adopt it. Please have a look. We hope that it's inspiring for you and useful for you to share with others in encouraging them to have a mentality for InnerSource.

Hey @rrrutledge 

I'm sure you're aware of this but just in case ... I'm in the process of working on the newsletter and I've noticed that the InnerSource Mentality isn't on the learning path page of the website ...

**Comment by CiaraFlanagan** [comment]
> Have I done this one before? https://resources.github.com/innersource/accelerate-2022/

Need to double check and add to August newsletter

**Comment by CiaraFlanagan** [comment]
> There is a new segment of the Learning Path that is live - [The InnerSource Mentality](https://innersourcecommons.org/learn/learning-path/introduction/09/). This segment shares a short and concise creed and commitment to InnerSource that is easy to understand and support and encourages all to adopt it. Please have a look. We hope that it's inspiring for you and useful for you to share with others in encouraging them to have a mentality for InnerSource.

Hey Russell

I did find the segment!
