### ISSUE TITLE
August Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#216]
We are preparing content for our August Newsletter.

Please share your suggestions for content. This can include:

News about your InnerSource project!
Any news about activities happening in the wider InnerSource community
Favorite InnerSource articles, videos or resources you have come across over the past month.
Learning Path updates
Pattern of the month
Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day Monday July 31.

**Comment by CiaraFlanagan** [comment]
Have I done this one before? https://resources.github.com/innersource/accelerate-2022/

**Comment by CiaraFlanagan** [comment]
https://medium.com/@justin.kalicharan/innersource-approach-benefits-usage-466876afde64

**Comment by CiaraFlanagan** [comment]
https://opensource.mercedes-benz.com/news/sponsor_innersource_commonsoss

**Comment by CiaraFlanagan** [comment]
Have I done this before? : https://www.linkedin.com/pulse/inner-source-deixei%3FtrackingId=axWuHYvLRIOnqogHzzIfgQ%253D%253D/?trackingId=l4HKZeRW4nWMzXyFnwFWnw%3D%3D

**Comment by CiaraFlanagan** [comment]
https://bitergia.com/blog/innersource/efficiency-and-transparency-with-innersource/

**Comment by CiaraFlanagan** [comment]
Suggested pattern of the month:  https://patterns.innersourcecommons.org/p/crossteam-project-valuation

waiting to see if anyone would like to nominate a different pattern

**Comment by CiaraFlanagan** [comment]
https://www.openchainproject.org/news/2023/07/27/webinar-55

**Comment by CiaraFlanagan** [comment]
New sponsor slide

**Comment by CiaraFlanagan** [comment]
Interview

**Comment by CiaraFlanagan** [comment]
https://dirkriehle.com/2023/07/31/the-business-impact-of-inner-source-and-how-to-quantify-it-csur-journal/

**Comment by jeffabailey** [comment]
Introduction to the InnerSource Program Office working group.

https://github.com/InnerSourceCommons/ispo-working-group

Take the blurb at the top of our repo, and invite people to join the working group.

We can summarize our metrics work and the overall direction of the working group.

☝️ will need a little work.

CC: @rrrutledge

**Comment by rrrutledge** [comment]
Sure - I’ll look at this today.

**Comment by rrrutledge** [comment]
In the past month, the ISPO Working Group has been spending time on _**metrics and KPIs**_.  Through conversation, we've outlined many key metrics, the goals that they support, and documented those as a graph on [this online board](https://miro.com/welcomeonboard/OFdjUVFkb2pNa2g0RWNYWUtkSXFYUkJ0MDZZc0dPbnY5NVV4R3o4dFl5Tk4zREZHQTNYelNWY3pPZGxTaDFOanwzMDc0NDU3MzQ3MDQ2NDMwMjIyfDI=?share_link_id=346540196504).  Check it out and add in your own scenarios to contribute!  We're working now on translating this graph to a clear and published online version with implementation suggestions.

The overall purpose of the ISPO working group is to support InnerSource Program Offices (ISPOs) with materials needed to establish themselves, educate partners and stakeholders, and scale InnerSource in their respective company. This material could be directed towards senior leaders, managers, or individuals in a variety of roles. Check out our [CONTRIBUTING.md](https://github.com/InnerSourceCommons/ispo-working-group/blob/main/CONTRIBUTING.md) for specifics on how you can get involved.

**Comment by CiaraFlanagan** [comment]
Countdown to RFPs for InnerSource Summit - following advice - changed to call out for volunteers

**Comment by CiaraFlanagan** [comment]
https://sessionize.com/2023-all-day-devops/

**Comment by CiaraFlanagan** [comment]
Thanks for the suggestions @rrrutledge and @jeffabailey! These have been added to the August newsletter.
