### ISSUE TITLE
Collect feedback from newcomers

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#22]
Before we start this task, https://github.com/InnerSourceCommons/marketing-wg/issues/18 needs to be done.

## Purpose

We want to improve the experience that newcomers have, when they join the InnerSource Commons community.
To do that, we need to know more about what their experience actually is.

## How?

When a newcomer joins, we point them to the **InnerSource Commons 101** document (that we are developing in https://github.com/InnerSourceCommons/marketing-wg/issues/18).

When a newcomer has been in the community for a couple of weeks/months, we want to ask them for their feedback about their experience.

Based on that feedback, we want to find new ways to improve the onboarding experience. 
(we will write new tasks/issues, based on this feedback)

**Comment by spier** [comment]
Questions:

- how did you find out about the InnerSource Commons?

**Comment by spier** [comment]
Sometimes this is referred to as a "Friction Log":
https://cwiki.apache.org/confluence/display/EDI/Friction+Log+Insights+and+Recommendations+Report+Template

**Comment by spier** [comment]
This work can start now, as the ISC 101 is published: http://innersourcecommons.org/isc-101

**Comment by lenucksi** [comment]
> Questions:
> 
> * how did you find out about the InnerSource Commons?

I would add one demographic question
* Where would you say your current work role is located: Developer, DevOps/Operations/Automation, Program Management/Project Management, Line Management, Other

We need to ensure credible anonymity here for the survey, after all we're just into the data here. 
We should also add a welcoming suggestion to also just highlight ask any of the ISCF members with their questions such that they have someone to go to for improvements if they do not want to bring that to the full public.
However: It should be welcome, safe and the go-to-method to just bring things up in the public channels. After all, that is what they are for.

**Comment by rrrutledge** [comment]
No one has done anything with this for a while.
