### ISSUE TITLE
September Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#223]
We are preparing content for our August Newsletter.

Please share your suggestions for content. This can include:

News about your InnerSource project!
Any news about activities happening in the wider InnerSource community
Favorite InnerSource articles, videos or resources you have come across over the past month.
Learning Path updates
Pattern of the month
Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day Wednesday August 30.

**Comment by rrrutledge** [comment]
@spier talking about InnerSource on a podcast.

**Comment by CiaraFlanagan** [comment]
CFP for Summit

https://docs.google.com/forms/d/1CYd_AYJ6cAWNAcaecSsgDCGdKYSMIcByb-RKZ0koQyw/edit

**Comment by CiaraFlanagan** [comment]
> CFP for Summit
> 
> https://docs.google.com/forms/d/1CYd_AYJ6cAWNAcaecSsgDCGdKYSMIcByb-RKZ0koQyw/edit

Hey @spier - is there a link to this podcast anywhere?

**Comment by CiaraFlanagan** [comment]
https://www.cos.io/blog/strategy-for-culture-change

**Comment by CiaraFlanagan** [comment]
Pattern of the month:  https://patterns.innersourcecommons.org/p/release-process

**Comment by spier** [comment]
> Hey @spier - is there a link to this podcast anywhere?

Not yet. I cannot promize if the podcast will even be published in time for the September Newsletter.
Will comment here again if it goes live.

**Comment by rina-kat0** [comment]
Case Study: KINTO Technologies’ InnerSource Implementation
https://blog.kinto-technologies.com/posts/2023-07-25-innersource-en/

**Comment by spier** [comment]
Thank you for sharing this @rina-kat0.

I was wondering if your approach of testing InnerSource on your techblog could be considered an implementation of the pattern [Start as an Experiment](https://patterns.innersourcecommons.org/p/start-as-experiment) (also available in Japanese translation if you prefer that)?

If you would like to chat more about this, you are also more than welcome to join us in [our slack](https://innersourcecommons.org/slack). Find me in the `#jp-general` channel in slack :)

**Comment by yuhattor** [comment]
@rina-kat0 AMAZING!! 

Thank you for your outstanding work on InnerSource at KINTO Technologies.
Please join us on Slack. Both the English and Japanese communities welcome you 🎉

**Comment by yuhattor** [comment]
And why not share your success stories with the community? There is a place to share it in Japanese or English😄

**Comment by CiaraFlanagan** [comment]
Updated CFP for summit

https://docs.google.com/forms/d/e/1FAIpQLSdL6vavOIoDCI9ut6QMLY1TG8dN6lf9Rn6MZTK_wkJ1mu837g/viewform

**Comment by spier** [comment]
ISC expanding into other local communities - translations of website and patterns to Brazilian Portuguese.
https://innersourcecommons.org/pt-br/
https://patterns.innersourcecommons.org/v/pt-br/

As this is one of the strategic goals of the ISC, lets make sure we phrase this properly and make this a big win :)

**Comment by CiaraFlanagan** [comment]
https://customers.microsoft.com/en-us/story/1671022200964097988-connect-panasonic-discrete-manufacturing-azure-en-japan

**Comment by CiaraFlanagan** [comment]
Other events: FINOS call: FINOS call on September 12 on InnerSource license generation

**Comment by CiaraFlanagan** [comment]
red hat sponsorship

**Comment by CiaraFlanagan** [comment]
> ISC expanding into other local communities - translations of website and patterns to Brazilian Portuguese. https://innersourcecommons.org/pt-br/ https://patterns.innersourcecommons.org/v/pt-br/
> 
> As this is one of the strategic goals of the ISC, lets make sure we phrase this properly and make this a big win :)

Hey there @spier - do we have anything specific (like a document) that I can refer to around the InnerSource strategic goals?  No problem if one isn't publicly available ....

**Comment by spier** [comment]
> > ISC expanding into other local communities - translations of website and patterns to Brazilian Portuguese. https://innersourcecommons.org/pt-br/ https://patterns.innersourcecommons.org/v/pt-br/
> > As this is one of the strategic goals of the ISC, lets make sure we phrase this properly and make this a big win :)
> 
> Hey there @spier - do we have anything specific (like a document) that I can refer to around the InnerSource strategic goals? No problem if one isn't publicly available ....

Not that I am aware of.

@rrrutledge are you aware of anything like this that we have shared publicly?

**Comment by CiaraFlanagan** [comment]
> > > ISC expanding into other local communities - translations of website and patterns to Brazilian Portuguese. https://innersourcecommons.org/pt-br/ https://patterns.innersourcecommons.org/v/pt-br/
> > > As this is one of the strategic goals of the ISC, lets make sure we phrase this properly and make this a big win :)
> > 
> > 
> > Hey there @spier - do we have anything specific (like a document) that I can refer to around the InnerSource strategic goals? No problem if one isn't publicly available ....
> 
> Not that I am aware of.
> 
> @rrrutledge are you aware of anything like this that we have shared publicly?

Thanks for getting back to me @spier

**Comment by rrrutledge** [comment]
Nothing public yet but I am working to have it by end of calendar year.
