### ISSUE TITLE
October Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#227]
We are preparing content for our October Newsletter.

Please share your suggestions for content. This can include:

News about your InnerSource project!
Any news about activities happening in the wider InnerSource community
Favorite InnerSource articles, videos or resources you have come across over the past month.
Learning Path updates
Pattern of the month
Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day Friday September 29.

**Comment by CiaraFlanagan** [comment]
https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/tech-forward/why-your-it-organization-should-prioritize-developer-experience

**Comment by CiaraFlanagan** [comment]
https://www.youtube.com/watch?v=9qNWtGe6Qcc

**Comment by CiaraFlanagan** [comment]
did we post this before?

https://dzone.com/articles/inner-source?utm_campaign=innersource-efficiency-and-quality-of-open-source-in-the-corporate-world&utm_medium=social_link&utm_source=missinglettr-twitter

**Comment by CiaraFlanagan** [comment]
did we post this before?

https://www.linkedin.com/pulse/why-you-should-invest-innersource-rafael-battesti/

**Comment by CiaraFlanagan** [comment]
https://www.linkedin.com/pulse/agile-incomplete-manifesto-john-mark-walker%3FtrackingId=XNBS07W9SGq6MyCPwyGRGw%253D%253D/?trackingId=n7W5ohqE6fqgad1cs3MnfQ%3D%3D

**Comment by CiaraFlanagan** [comment]
https://www.bqprime.com/technology/gartner-identifies-top-strategic-technology-trends-in-software-engineering

**Comment by CiaraFlanagan** [comment]
https://www.gartner.com/en/newsroom/press-releases/gartner-identifies-the-top-strategic-technology-trends-in-software-engineering-trends-for-2023

**Comment by CiaraFlanagan** [comment]
Proposing Pattern of the Month: Document Your Guiding Principles

https://patterns.innersourcecommons.org/p/document-your-guiding-principles

**Comment by CiaraFlanagan** [comment]
https://engineeringkiosk.dev/podcast/episode/90-inner-source-open-source-best-practices-zur-besseren-zusammenarbeit-zwischen-teams/?pkn=twitter

**Comment by CiaraFlanagan** [comment]
https://www.codu.co/articles/unlocking-collaboration-with-innersource-fsn9aouk

**Comment by CiaraFlanagan** [comment]
https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/tech-forward/why-your-it-organization-should-prioritize-developer-experience

**Comment by spier** [comment]
i was invited to speak at a podcast about InnerSource. This went live now.
Please note that this is in German, but the feedback I got from the Board is that we have a large enough part of our community that speaks German, so it might be still worthwhile to share.

Would be great if it could be included in the newsletter!

Engineering Kiosk: #90 Inner Source: Open Source Best Practices zur besseren Zusammenarbeit zwischen Teams - mit Sebastian Spier
https://engineeringkiosk.dev/podcast/episode/90-inner-source-open-source-best-practices-zur-besseren-zusammenarbeit-zwischen-teams/

**Comment by CiaraFlanagan** [comment]
Hey @dellagustin @gruetter 

I will share the link to OSPOlogyLive Frankfurt in the October newsletter again. https://community.linuxfoundation.org/events/details/lfhq-ospology-european-chapter-presents-ospologylive-frankfurt/

If there is anything specific you want to add about the InnerSource and Culture talk or the potential for a roundtable on InnerSource, please feel free to add some text/content here.

**Comment by CiaraFlanagan** [comment]
https://podcast.opensap.info/open-source-way/2023/09/27/the-todo-group-talk-openly-develop-openly/

**Comment by CiaraFlanagan** [comment]
https://www.redhat.com/en/blog/ins-and-outs-innersource

**Comment by CiaraFlanagan** [comment]
The state of InnerSource survey is live

https://innersourcecommons.org/learn/research/state-of-innersource-survey-2022-2023/

**Comment by dellagustin-sap** [comment]
Thank you @CiaraFlanagan ! Sorry I did not manage to propose a text in time, but it is great that the OSPOlogy Live event was shared.

**Comment by CiaraFlanagan** [comment]
Report on metrics

**Comment by CiaraFlanagan** [comment]
> Thank you @CiaraFlanagan ! Sorry I did not manage to propose a text in time, but it is great that the OSPOlogy Live event was shared.

No problem @dellagustin-sap! I hope the event is a great success!
