### ISSUE TITLE
Kick-Start the Fall Summit Committee

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#23]
Kick-Start the Fall Summit Committee based on Daniel's work for the [Spring Summit 2020](http://innersourcecommons.org/events/isc-spring-2020/).

## Notes

- Document the Expectations of the Stakeholders
- Write-up what we want
- Hats: ? Host, Hosting Committee
- What belongs to the committee and what to the host
- CFP
- Get the recordings
- Run the stream

## TODO

+ Same card for the Asia Summit

**Comment by spier** [comment]
@dicortazar does this card have to be on the board of the Marketing group? Or is there a separate place where we should move this to?

**Comment by dicortazar** [comment]
I think we can go initially for the marketing working group but we can decide on this during the marketing meeting itself. 

Sorry for the delay with this answer!

**Comment by dicortazar** [comment]
We can indeed go for the CFP at https://docs.google.com/forms/d/e/1FAIpQLScIcPEotrClmqLYaiFv-rGei6R2r8jbP2a-oPrC8NSWA0dEmQ/viewform?usp=sf_link

**Comment by claredillon** [comment]
@dicortazar kicked off the process. The meetings have now been scheduled and marketing-wg  and general Slack channels also notified.
