### ISSUE TITLE
Have a place for sharing content publicly

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#24]
- Make our website Blog capable
- Or use a Planet aggregator thing.

This should be helpful: https://docs.google.com/spreadsheets/d/1yd8ASzJvPEQ1l1BgQWtrFzJUwrfDdvMUN-xqltkfQnU/edit#gid=0

**Comment by spier** [comment]
@lenucksi what is "Planet aggregator"?

**Comment by spier** [comment]
@claredillon do you know where the need for "having something like a blog" came from? i.e. any particular problem that we are trying to solve, or any situation where somebody said "we need a blog"?

I want to make sure that we are solving for the right problem here :)

**Comment by lenucksi** [comment]
> @lenucksi what is "Planet aggregator"?

A piece of software that aggregates multiple RSS feeds into one blog and one RSS feed. Used by e.g. planet.gnome.org. Used to be popular in the 2000s, still good software, still in use by many.

**Comment by lenucksi** [comment]
> @claredillon do you know where the need for "having something like a blog" came from? i.e. any particular problem that we are trying to solve, or any situation where somebody said "we need a blog"?
> 
> I want to make sure that we are solving for the right problem here :)

I can also chip in here: 
- One use case was: "We want to publish the incorporation, the 501(c)3 success, regular interesting things that people came up with and "let's write a blog article about it - but where?"
- Similar to the ASF blog.

**Comment by spier** [comment]
Thanks for the input.

When we start on this, lets consider how we would to treat existing postings like:
- [articles](http://innersourcecommons.org/resources/articles/)
- [news](http://innersourcecommons.org/news/)

My take would be to have all of these things in a single "blog", maybe with different content types i.e.
- **original blog posts** - hosted on innersourcecommons.org
- **links** to other posts and content - just like what we have in [articles](http://innersourcecommons.org/resources/articles/) today
- **press releases** - we only have one press release so far, so I would not worry about that content type yet

**Comment by lenucksi** [comment]
Regarding the content types and variations on aggregation:
- Modern blog systems know tags and can often produce feeds based on those tags as well as online aggregations by category.
- That way we can have huge feed with everything that likely is more like a Twitter feed and another that is decently sorted and useful for reference, e.g. for the articles.
- What do you reference to as "content type" here? `application/pdf` `application/json`  `text/html` ? 

Another thing would be making adding articles or syndicating them from other authors that are members easier.
Something that might make things easier is this thing here: https://www.netlifycms.org/

**Comment by claredillon** [comment]
In the last discussion about this, we decided to use the LinkedIn Company page for any news/blogs/announcements. @Clcoffey confirmed that admins of the company page can post articles as the company, which gets around character limits on the Company page updates.
