### ISSUE TITLE
Addition of new sponsor

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceMarketing#247]
What does this mean?

**Comment by CiaraFlanagan** [comment]
Hi @rrrutledge 

I started this as a potential issue when a recent sponsor came on board.  However, I haven't fully captured what's involved yet.

What do you think of me adding this as a future task for the project board in relation to sponsor announcements?

**Comment by rrrutledge** [comment]
The next time we do a Sponsor let’s make it alongside processing that sponsor.  I think it will be soon.

**Comment by CiaraFlanagan** [comment]
Agreed!
