### ISSUE TITLE
November Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#248]
We are preparing content for our November Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day Friday October 27.

**Comment by CiaraFlanagan** [comment]
https://www.linkedin.com/pulse/pushing-innersource-engagement-katie-schueths/

**Comment by CiaraFlanagan** [comment]
https://www.linkedin.com/pulse/how-gig-marketplace-sparks-collaborative-success-przemek-malirz%3FtrackingId=PA7I33bAQviwWg%252BGB07jgA%253D%253D/?trackingId=PA7I33bAQviwWg%2BGB07jgA%3D%3D

**Comment by mishari** [comment]
We're organizing a joint FOSS4G Thailand x State of the Map Asia event on 16th-18th November (same days as the InnerSource Summit) if you're into geospatial technologies and/or Open Street Map and in the region, then this event is for you.

More information and registration at https://2023.foss4g.in.th/

**Comment by CiaraFlanagan** [comment]
https://innersource.flutter.com/

**Comment by CiaraFlanagan** [comment]
https://newsletter.cote.io/p/the-only-people-who-dont-like-metrics?utm_source=post-email-title&publication_id=50&post_id=137837880&utm_campaign=email-post-title&isFreemail=true&r=2ijd0w&utm_medium=email

**Comment by rrrutledge** [comment]
https://pages.xpirit.com/hubfs/Xpirit/Xpirit%20Magazine/XPRT%20magazine%2015/Xebia_Xpirit_XPRT_magazine_%2315_2023.pdf

**Comment by CiaraFlanagan** [comment]
https://www.automotiveit.eu/strategy/new-work/was-macht-eine-inner-source-managerin-398.html

**Comment by dellagustin-sap** [comment]
Hi @CiaraFlanagan , on October 27th I presented in Portuguese at the Angola Open-Source Fest (https://fest.aosc.social/).
Title of the presentation: "InnerSource, InnerSource Program Offices e como funciona a iniciativa de InnerSource na SAP"
here is the recording of the broadcast https://www.youtube.com/live/0xIj5SZRPe8?si=NyCfz1eYwbEsihyO&t=15239, it links to the timestamp 04:13.59 where my presentation starts.
It goes until 04:51:06.
Is it still possible to include on the November newsletter?

**Comment by CiaraFlanagan** [comment]
> Hi @CiaraFlanagan , on October 27th I presented in Portuguese at the Angola Open-Source Fest (https://fest.aosc.social/). Title of the presentation: "InnerSource, InnerSource Program Offices e como funciona a iniciativa de InnerSource na SAP" here is the recording of the broadcast https://www.youtube.com/live/0xIj5SZRPe8?si=NyCfz1eYwbEsihyO&t=15239, it links to the timestamp 04:13.59 where my presentation starts. It goes until 04:51:06. Is it still possible to include on the November newsletter?

Absolutely! I'll be delighted to share it.

**Comment by CiaraFlanagan** [comment]
https://xpirit.com/innersource/

**Comment by CiaraFlanagan** [comment]
link to innersource to opensource talk at github universe?

**Comment by CiaraFlanagan** [comment]
https://reg.githubuniverse.com/flow/github/universe23/sessioncatalog/page/sessioncatalog/session/1686003617586001r1wE

**Comment by CiaraFlanagan** [comment]
https://newsletter.cote.io/p/the-only-people-who-dont-like-metrics?utm_source=post-email-title&publication_id=50&post_id=137837880&utm_campaign=email-post-title&isFreemail=true&r=2ijd0w&utm_medium=email

**Comment by rrrutledge** [comment]
Over half of repondants have an active InnerSource program: https://github.blog/2023-11-08-the-state-of-open-source-and-ai/

**Comment by rrrutledge** [comment]
Over half of respondents spend time monthly contributing to InnerSource: https://www.linuxfoundation.org/hubfs/LF%20Research/FINOS%20State%20of%20Open%20Source%20in%20Financial%20Services%202023%20-%20Report.pdf?hsLang=en
