### ISSUE TITLE
Marketing WG | Working Agreement and Tools

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#25]
Working Agreement and Tools of the Marketing & Outreach group

When talking to @claredillon, she and I realized that the newly formed Marketing & Outreach group has not had a discussions about the tools that we are using, and how we are using them.

I volunteered to document this, and run it by the group in the next meeting.

**Update:**

[Working Agreement and Tools - Marketing Working Group](https://docs.google.com/document/d/1jWH9uqEqhXMFz69-p5h-TwD5pBW6h6gvrmgJB9qc92Y/edit)

**Comment by spier** [comment]
## Name

The **Marketing & Outreach Working Group** is also called **Marketing WG** as a short form.

It was started in May 2020, so all is very new and up for debate :)

## Working Agreement

* **mission**: We work towards our mission statement (see TBD https://github.com/InnerSourceCommons/marketing-wg/issues/10), as measured by the success criteria we defined for ourselves (see TBD https://github.com/InnerSourceCommons/marketing-wg/issues/3).
* **contribute where you can**: We are a group of volunteers, so anybody can freely pick and chose the things that you would like to contribute to. Do as much or as little as you like.
* **stop starting, start finishing**: Given the limited time we have, we try to finish things that we already started, before starting new things. The Marketing WG Board (see Tools) will help us to do so.
* **we make our own decisions**: The working group does not have a dedicated leader that makes decisions. We are all empowered to make decisions on our own, and try to reach consensus in the group where that seems important. Sometimes we may ask the Board of the InnerSource Commons for confirmation.
* **meetings**: If you have time to join our sync meeting every 2 weeks that is awesome, but not a requirement (see Tools).

## Tools

- the [Marketing WG Board](https://github.com/InnerSourceCommons/marketing-wg/projects/1) (in GitHub) shows what we are currently working on
- we keep shared documents in the [Marketing & Outreach gDrive folder](https://drive.google.com/drive/u/0/folders/1Bsb6p_0y_xhbJOdzz6hMShCNUovUVXJt)
- most communication is handled in the #marketing channel in Slack, in conversations on GitHub issues, or comments on gDrive documents
- we have a sync meeting every two weeks at alternating times to facilitate our global community
- we do not use the InnerSource Commons mailing list (there might even not be such a thing as a mailing list any more)

**Comment by claredillon** [comment]
This is great @spier - it should help people (and us ;) get more clarity on how we can best operate.

**Comment by spier** [comment]
If there is no major disagreement with this proposal, I would turn this into a gDoc, put it into our gDrive folder.

Then we can:
- point new WG members to this doc
- add new points to this doc as we uncover new ways of collaborating (e.g. we might describe a bit how we go about facilitating our 2-weekly meeting)

**Comment by spier** [comment]
Feedback from Danese: 
We encourage everybody to support a frictionless process by improving things that seem to be broken.
If you see anything in the status quo that does not seem to be working, just challenge it.

**Comment by spier** [comment]
We have moved this description into this google doc:
https://docs.google.com/document/d/1jWH9uqEqhXMFz69-p5h-TwD5pBW6h6gvrmgJB9qc92Y/edit

I will continue on it there, and share it with new WG members.

**Comment by spier** [comment]
I will use lazy consensus on this one.

i.e. if I don't hear any strong disagreement by next meeting, I will add this doc to the channel header and also share it in #general to see if anybody else wants to join our WG.

**Comment by claredillon** [comment]
Updated Google doc above with descriptions of Lazy consensus, Asking for input with lazy consensus, voting and board votes and guidelines on how to choose which approach.

**Comment by spier** [comment]
In order to get this issue done, I have asked for input from all in #marketing Slack. 

I am using Lazy Consensus, with a 72 hour time window. i.e. on Friday this time I will work in all feedback, and if there are no major concerns I will consider this issue done.

**Comment by spier** [comment]
I did not receive any further feedback.

I will leave my own comments in the doc open, so that others can still see them.

I am also linking to this doc from #marketing so that new people can find it and we can keep evolving it.
