### ISSUE TITLE
Adding Shell as a sponsor to ISC

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#254]
Checklist for new Sponsors:

## Gathering contact details, logos and information from new sponsor
Once a new sponsor is confirmed, an email address for a key contact will be shared with you by the Executive Director. At this point, you will be in charge of gathering the information needed for ongoing communications, updating the sponsor and content for ISC announcements.

- [ ] Check with the Executive Director if the sponsor will be a Partner or a Supporter of InnerSource Commons.
- [x] Go to the Sponsors folder (https://drive.google.com/drive/folders/1thHxyqFYfolfPkp7pe_ZccmyXMedKCEA?usp=sharing) in the Marketing and Outreach Drive.
- [x] Save a new copy of the Sponsor Information Doc as 'Sponsor Info [Company Name]. (https://docs.google.com/document/d/118ESzAGnbQB2PkRemAQU0h88zjqMoMBj/edit#heading=h.pjw1t43glwqq) 
- [x] Use the template email: 'Template email: Contacting Sponsors to obtain key information for sponsor announcements' in the Sponsor Comms doc (https://docs.google.com/document/d/1d6my5hWMBJJFfRaUU0CnAZzmnIcST58HDN6VTgHY7Yc/edit?usp=sharing), to make initial contact with Sponsor requesting information. In the email, share the link to the Sponsor Information Doc saved with the sponsor's name.
- [ ] When the sponsor responds, add their information in the 'Sponsor Contact Details' google sheet (https://docs.google.com/spreadsheets/d/1HVeVCb9V5lk6UfLZ3PZkTGvoYQcro5epmVahsFq7ucE/edit?usp=sharing).

## Update the 'New Sponsor Announcement Slide' for forthcoming announcements on social
When we post on social, we use a slide welcoming the new sponsor. This slide can be found on our canva site. You will need edit access for this site. The slide is used on our announcements on LinkedIn and on X. It can also be shared on the Executive Director's slack announcement to the general channel. Depending on the size or shape of the logo, the slide may need to be tweaked slightly.

- [ ] Go to Canva and find the 'Sponsor Announcements' file (https://www.canva.com/design/DAFmp4U436s/-IPHFFjXQBB2noCYikGjlw/edit?utm_content=DAFmp4U436s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)n)
- [ ] Duplicate the first slide
- [ ] Update text to either 'Partner' or 'Supporter'. 
- [ ] Add the new Sponsor's logo to the slide.
- [ ] Save the file and then download the new slide for future social announcements.

## Update the sponsors slide for Community Calls and events
We also use a specific slide that displays all our sponsors. This slide is used at the beginning of all our Community Calls and events and any other recordings. **The updated sponsor slide must be used at the next ISC Community Call or relevant event.**

- [ ] Go to Canva and find the ISC Sponsors presentation (https://www.canva.com/design/DAFB4TbUaCw/b-3uIuKwn4nM2Dxq-KAKRg/edit?utm_content=DAFB4TbUaCw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [ ] Duplicate the first slide
- [ ] Add the new Sponsor to the slide under the relevant heading (Our Partners or Our Supporters)

## Writing announcement content
An announcement using the 'New Sponsor Announcement' Slide is made on LinkedIn and Twitter. Once that content is posted, the Executive Director (or President) will make the announcement on the general slack channel and include links to the two social posts. This needs to be drafted and signed off before the sponsor's logo and information is added to the website.

- [ ] Go to 'Sponsor Announcements' file (https://docs.google.com/document/d/13MwFKCEi7Yfinbn8hyUdJe07ADoNXi6a/edit?usp=sharing&ouid=112227356091295695995&rtpof=true&sd=true).
- [ ] Start at the top of the document and follow the format of the other sponsor announcements with the: 
- Month of the Announcement
- [Company Name]
- Add Sponsor Announcement Slide
- Add text for LinkedIn post
- Add text for Twitter post
- Add text for Slack channel post
- [ ] Share content with Executive Director for final sign off
- [ ] Agree with Executive Director on the schedule for him/her making the slack announcement and when to update the sponsors page on the website.

## Update the Website
Follow the steps below to add the sponsor's logo and company name to 'Our Sponsors' webpage (https://innersourcecommons.org/about/sponsors/).

- [ ] Rename the logo file of the new Sponsor as: [company_name].png
- [ ] Upload this file in the static/images/logos folder on the website 
- [ ] Open the sponsors.md file located in the folder: content/about
- [ ] Go to the relevant section in this file (if adding a Partner go to the first section - Our Partners. If adding a Supporter go to the second section - Our Supporters.
- [ ] Copy and paste the following line of code in the correct place, following the alphabetical order:
{{< company name="[company name]" image="/images/logos/[company_name].png" >}}{{< /company >}}
- [ ] Save your changes and make sure to test the result before creating the pull request

## Update community channels and social media
Ideally, the social posts will happen on the same day that the sponsors page is updated. The posts that include the new sponsor announcement slide should be scheduled in the following order:
- [ ] Create a LinkedIn post tagging the sponsor and relevant key contacts
- [ ] Create a Twitter post tagging the sponsor and relevant key contacts
- [ ] Slack post on general channel (which contains the links the LinkedIn and Twitter announcement). The sponsor and their key contacts should also be tagged in this post.

## Update new sponsor on Announcements
- [ ] Use the Template email: 'Notifying Sponsors when announcements go live' in the Sponsor Comms doc (https://docs.google.com/document/d/1d6my5hWMBJJFfRaUU0CnAZzmnIcST58HDN6VTgHY7Yc/edit?usp=sharing) to notify sponsor that the announcement is live! 

## Include in the next Newsletter
- [ ] An issue is created every month for topics to be added to the newsletter. Please comment on the issue and mention the new Sponsor. This announcement should be at the top of the newsletter.

## Update new sponsor on Newsletter Announcement
- [ ] Use the Template email: 'Notifying Sponsors when announcement is posted in Newsletter' in the Sponsor Comms doc (https://docs.google.com/document/d/1d6my5hWMBJJFfRaUU0CnAZzmnIcST58HDN6VTgHY7Yc/edit?usp=sharing) to notify sponsor that the announcement is live!
      
## Other things to consider
- [ ] Is the new sponsor included on the InnerSource in Action Page?
- [ ] Is the new sponsor providing any services and if so would they like to be listed in the Services Directory?

**Comment by rrrutledge** [comment]
Shell has an Internal InnerSource event happening the week of January 15.  Let's ask them again about this after Christmastime, if we dont' heard from them then ask them in the week of January 22nd.

**Comment by rrrutledge** [comment]
Don't worry about this for now.  They are content to be a "silent" sponsor for the moment.
