### ISSUE TITLE
Adding Red Hat to Services Directory

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceMarketing#255]

**Comment by rrrutledge** [comment]
Thank you for making this issue, @CiaraFlanagan

**Comment by CiaraFlanagan** [comment]
@rrrutledge I've sent a reminder to Red Hat and cc'd you in.

**Comment by rrrutledge** [comment]
@CiaraFlanagan remind me - are we ready to pick this up again?

**Comment by CiaraFlanagan** [comment]
@rrrutledge - I've just sent a reminder to Red Hat and I've added that they can get in touch with me anytime they want to start moving on this.

**Comment by CiaraFlanagan** [comment]
@rrrutledge - Red Hat has been in touch by email to get the ball rolling. 

Waiting on their content and may have a short meeting to discuss if they require so.

**Comment by CiaraFlanagan** [comment]
I've created an issue and waiting on @andrea-kyurchiev to create the PR. @rrrutledge, can you merge this if/when it becomes a PR, that would be great.
