### ISSUE TITLE
Move meeting to an APAC friendly time every other meeting

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#26]
Mishari [made a great point](https://innersourcecommons.slack.com/archives/CUWFGQJ8K/p1594036725002300) that we. should try to find a more APAC-friendly meeting date/time, so that we can include people from that region.

Currently most participants are in Europe, with 1 in the Americas and 1 in APAC.

Based on that we decided in our last session (July 6th) that we would keep rotating the meeting time every other meeting, so that people from the Americas/APAC at least have a chance to join one meeting per month.

## Meeting time

It is held every two weeks at alternating times to facilitate our global community:

Early: 12pm GMT / 1pm CET / 7am EST (more APAC friendly)
Late: 4pm GMT / 5pm CET / 11am EST (more Americas friendly)

**Comment by claredillon** [comment]
ISC Calendar invites have been updated as discussed. First 12pm meeting will be July 2020.
