### ISSUE TITLE
Error with slack 'join' link for ISC slack

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#261]
Our link to join our slack workspace has an issue: https://innersourcecommons.slack.com/archives/C04PXKRN4  (this is the link for the general channel on slack).

When a potential member tries to create a new account, they are brought to this page:  https://innersourcecommons.slack.com/signup?redir=%2Farchives%2FC04PXKRN4%3Fname%3DC04PXKRN4#/domain-signup

BUT: they can only create a slack account with an email domain that's already recognized ... (see image below). 

This was flagged by someone who couldn't join our slack with their gmail address ...

![image](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/101422261/b572f114-7036-497d-9589-f7c30e0c3a4e)

**Comment by rrrutledge** [comment]
@jeffabailey were you also noticing some weirdness around our join link?

**Comment by jeffabailey** [comment]
> @jeffabailey were you also noticing some weirdness around our join link?

Yes, though I did not see the reported error.

I saw this error on my iPhone.

![image](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/776901/cf6e5231-7cca-44a6-801b-34b02bed34ed)

**Comment by rrrutledge** [comment]
We changed the link.  @jeffabailey does that work for you now?

**Comment by jeffabailey** [comment]
> We changed the link. @jeffabailey does that work for you now? So yes, from my point of view it works. :)

When navigating here with my phone: https://innersourcecommons.org/community/

I see the expected message: 

![image](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/776901/7bd3a0e3-ab32-40bf-989e-7f116b9b67f6)

**Comment by rrrutledge** [comment]
Great!
