### ISSUE TITLE
January 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#263]
We are preparing content for our January 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day Sunday, January 3rd 2024.

**Comment by CiaraFlanagan** [comment]
https://innersourcecommons.gitbook.io/managing-innersource-projects/v/m-gl/

See notes in slack (learning path?)

**Comment by rrrutledge** [comment]
InnerSource has been included in the Gartner Hype Cycle for Software Engineering for 2023 
[https://www.gartner.com/en/newsroom/press-releases/2023-11-28-gartner-hype-cycle-sho[…]nstream-adoption-in-software-engineering-in-two-to-five-years](https://www.gartner.com/en/newsroom/press-releases/2023-11-28-gartner-hype-cycle-shows-ai-practices-and-platform-engineering-will-reach-mainstream-adoption-in-software-engineering-in-two-to-five-years)

**Comment by CiaraFlanagan** [comment]
https://www.linkedin.com/pulse/why-innersource-starts-documentation-addie-girouard-ebric/

**Comment by CiaraFlanagan** [comment]
Add newsletter sign up link at bottom of newsletter.  Also double check to see if mailchimp has a subscribe / unsubscribe button for newsletter.

**Comment by CiaraFlanagan** [comment]
Pattern of the Month: Core Team (waiting for feedback from Patterns Working group)

**Comment by CiaraFlanagan** [comment]
Great post calling out translation of InnerSource Commons materials to Galician!
https://amtega.xunta.gal/gl/nova/xunta-traduce-ao-galego-guias-internacionais-de-boas-practicas-para-proxectos-de-software-de

**Comment by CiaraFlanagan** [comment]
Summit Playlist

**Comment by CiaraFlanagan** [comment]
Double check bottom of newsletter to ensure it's consistent with new sign up to our newsletter
