### ISSUE TITLE
Change "Mailing List" to "Newsletter" on the website

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceMarketing#264]
"Newsletter" sounds nicer.

**Comment by dellagustin-sap** [comment]
Tracing back to the discussion that originated this: https://innersourcecommons.slack.com/archives/CUWFGQJ8K/p1701423443958719
This is ephemeral, as slack messages are only available for 90 days.

As pointed by @rrrutledge there, there is a Sign Up from in the website at http://innersourcecommons.org/:
![image](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/54676965/09f4b9f5-9f81-4877-a724-fce66af00f26)

The original message from me was:
> There is something I cannot find the newsletter body (in general), information on how to subscribe to it.
> Use cases:
> * I forward the mail to other people
> * I share the link on internal forums
> Did I miss it?

Inspecting the form, it is a POST to https://innersourcecommons.us1.list-manage.com/subscribe/post?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2, but I don't know if this is a stable link I can share.

**Comment by rrrutledge** [comment]
@CiaraFlanagan will put something in the newsletter footer with instructions on how to sign up if it has been forwarded to you.

First check if MailChimp gives us some special change for subscribing and unsubscribing.

**Comment by CiaraFlanagan** [comment]
@rrrutledge @dellagustin-sap  I've added a link to the newsletter footer to facilitate new subscriptions.

We still need to update the website and replace 'mailing list' with 'newsletter'.  Do you want me to do that? (Russ - You had said that you would do that so just give me the go ahead.)

**Comment by rrrutledge** [comment]
Thanks for the reminder - yes I’ll do it.

**Comment by rrrutledge** [comment]
I took a look at this, but I don't think that I should do it.  We need to update other languages as well, which is more than I should try to coordinate.
