### ISSUE TITLE
January Newsletter

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceMarketing#273]

**Comment by rrrutledge** [comment]
Great post calling out translation of InnerSource Commons materials to Galician!
https://amtega.xunta.gal/gl/nova/xunta-traduce-ao-galego-guias-internacionais-de-boas-practicas-para-proxectos-de-software-de

**Comment by CiaraFlanagan** [comment]
Summit Playlist

**Comment by rrrutledge** [comment]
This can be moved to `Done`?
