### ISSUE TITLE
February 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#274]
We are preparing content for our February 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day: Tuesday January 30th  2024.

**Comment by misappi** [comment]
I suggest to add the blog post "[Cultivating InnerSource at SAP](https://blogs.sap.com/2024/01/08/cultivating-innersource-at-sap/)". Let me know if you need more information. Thanks!

**Comment by rrrutledge** [comment]
@voongc and the creation of https://github.com/InnerSourceCommons/repo-template

**Comment by CiaraFlanagan** [comment]
https://www.linkedin.com/pulse/introducing-open-covenant-license-jeff-schulman-srxif/

**Comment by rrrutledge** [comment]
https://blogs.sap.com/2024/01/08/cultivating-innersource-at-sap/

**Comment by claredillon** [comment]
Unsurprisingly - I'd love a "final call" for the survey. Ideally we'd have all responses in by the end of the month! :)

**Comment by CiaraFlanagan** [comment]
https://medium.com/itautech/innersource-no-ita%C3%BA-desenvolvimento-colaborativo-como-alavanca-em-tecnologia-eefde9414022

**Comment by CiaraFlanagan** [comment]
https://www.infoq.com/jp/articles/organizational-resilience-documentation/

**Comment by plainschwarz-team** [comment]
Sorry for missing the deadline — hope that this can still make the newsletter:

FOSS Backstage will take place on March 4-5th in Berlin this year. You can find our program and all the relevant information on our website: https://24.foss-backstage.de/schedule/ 
This year we also have an additional day dedicated to UX & Design in Open Source on March 6th: https://24.foss-backstage.de/foss-backstage-design/

InnerSource Commons organized a meetup last year during FOSS Backstage; hopefully that is something that we can have again this year.

**Comment by CiaraFlanagan** [comment]
> I suggest to add the blog post "[Cultivating InnerSource at SAP](https://blogs.sap.com/2024/01/08/cultivating-innersource-at-sap/)". Let me know if you need more information. Thanks!

@misappi - Great blogpost! You'll see in the February newsletter.

**Comment by CiaraFlanagan** [comment]
> Sorry for missing the deadline — hope that this can still make the newsletter:
> 
> FOSS Backstage will take place on March 4-5th in Berlin this year. You can find our program and all the relevant information on our website: https://24.foss-backstage.de/schedule/ This year we also have an additional day dedicated to UX & Design in Open Source on March 6th: https://24.foss-backstage.de/foss-backstage-design/
> 
> InnerSource Commons organized a meetup last year during FOSS Backstage; hopefully that is something that we can have again this year.

No problem @plainschwarz-team! The event will be shared in our February newsletter, which will be posted in the next few days.

**Comment by misappi** [comment]
> > I suggest to add the blog post "[Cultivating InnerSource at SAP](https://blogs.sap.com/2024/01/08/cultivating-innersource-at-sap/)". Let me know if you need more information. Thanks!
> 
> @misappi - Great blogpost! You'll see in the February newsletter.

Thanks!

**Comment by plainschwarz-team** [comment]
> No problem @plainschwarz-team! The event will be shared in our February newsletter, which will be posted in the next few days.

Thanks so much @CiaraFlanagan!

**Comment by CiaraFlanagan** [comment]
Add information re: Indeed as a Supporter

**Comment by CiaraFlanagan** [comment]
Add second community call.

**Comment by CiaraFlanagan** [comment]
https://blog.tidelift.com/recap-2024-open-source-software-security-predictions-webinar

**Comment by CiaraFlanagan** [comment]
> Unsurprisingly - I'd love a "final call" for the survey. Ideally we'd have all responses in by the end of the month! :)

As agreed, we're leaving the final call for the survey off the February newsletter but other social was posted at the end of January.

**Comment by CiaraFlanagan** [comment]
change top banner of newsletter
