### ISSUE TITLE
Set up Tweetdeck to allow multiple ISC members manage innersourceorg handle

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#29]
Tweetdeck is a free tool which has a team function to allow for multiple people to manage a Twitter account. Currently Clare Dillon is managing the official ISC Twitter handle. 
- Need to set up Tweetdeck with team
- Identify other folks who would like to manage (Clare and Danese, others? Specifically be great to get volunteers in other timezones too). 
- Set them up.

**Comment by lenucksi** [comment]
This documents the team function for reference purposes: https://help.twitter.com/en/using-twitter/tweetdeck-teams

**Comment by claredillon** [comment]
This has now been completed and tested with Danese. We have the ability to add other contrirutors. [Our description of how Twitter works at the ISC ](https://docs.google.com/document/d/1l3XEqgwq8i17065fjJH9PkKpvIvW_ErarLp4UWhqmOU/edit?usp=sharing)has also been updated.
