### ISSUE TITLE
April Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#299]
We are preparing content for our April 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day: **Monday, April 1 2024**

**Comment by CiaraFlanagan** [comment]
Articles:
https://www.linkedin.com/pulse/innersource-after-pandemic-kan-tang/ 
10 minute read

**Comment by CiaraFlanagan** [comment]
Article: 
https://www.linkedin.com/pulse/inner-source-robert-sidor-tavbc/
4 minute read

**Comment by CiaraFlanagan** [comment]
Video: 
https://www.youtube.com/watch?v=ZBV-jhnARDw&list=PLq-odUc2x7i-ww77dGasjo-d54ohCAb8k&index=7
28 minute watch

**Comment by CiaraFlanagan** [comment]
Events:
https://bitergia.com/madrid-data-and-tapas-day-2024/

**Comment by CiaraFlanagan** [comment]
Events: 
https://eu.communityovercode.org/speakers/

**Comment by CiaraFlanagan** [comment]
Article: 
https://www.linkedin.com/pulse/accelerating-change-innersource-impact-addie-girouard-zbcyf/?trackingId=td8Kx63jS2yv%2BnRq6%2B%2BtyQ%3D%3D

**Comment by CiaraFlanagan** [comment]
Article: 
https://www.linkedin.com/pulse/theres-value-your-platform-jonny-williams-1gtce/?trackingId=ctybh9gVT2aW%2BjFONO6VQA%3D%3D

29 min read

**Comment by CiaraFlanagan** [comment]
Did we post this article before: 

https://github.blog/2023-11-08-the-state-of-open-source-and-ai/

**Comment by CiaraFlanagan** [comment]
Events - call for proposals:

Hello!
Let me introduce my self, I work in [ADEO](https://www.adeo.com/) (home depot for european markets) and I am in charge of organising our yearly summit (called DevSummit). We speak about tech, data and management.
Inner source is a very important topic for us so we are looking for speakers that want to share some knowledge about Inner Source. Maybe something that is working in your company, a new pattern or some return of experience, if you can give a talk, we would love to listen.
Conferences are in person mode in Lille , France. 3-5 June.  And we have budget for transportation and hotel.
You can submit your talk [here](https://docs.google.com/forms/d/1eqajGtYcFe8InRwHgzUSO2oG9-8pdWeerGgxeiUDnfc/viewform?edit_requested=true)
And of course you can contact me directly in PM if you have any questions
Thanks and have a great day
EDIT: Also, if you have some one that you think could be a good match for giving a talk, you can refer them on PM so I can contact them directly
https://docs.google.com/forms/d/1eqajGtYcFe8InRwHgzUSO2oG9-8pdWeerGgxeiUDnfc/viewform?edit_requested=true

**Comment by CiaraFlanagan** [comment]
Due Diligence Checklist:
Full post on the topic: https://lnkd.in/gDzaVFiY
 
▶ And the Due Diligence checklist: https://lnkd.in/gFRj5WWd

**Comment by dellagustin-sap** [comment]
Hello @CiaraFlanagan , following the Community Call [Cross-Product Architecture - Lessons Learned from Applying Conway’s Law](https://bit.ly/ISCSAP), which was not recorded, we have published a blog post on the same topic: https://community.sap.com/t5/technology-blogs-by-sap/cross-product-architecture-embracing-conway-s-law-for-better-software/ba-p/13648600
Could you please add it to the newsletter?

Proposed text: Blog post from Guilherme Dellagustin based on the Community Call with Jochen Rode, on how SAP is applying InnerSource best practices at scale for collaborative work on architectural and technical topics. The described working mode resonates with several InnerSource Patterns, such as Dedicated Community Leader, Transparent Cross-Team Decision Making using RFCs and many others.

cc @OliveCannon

**Comment by rrrutledge** [comment]
https://www.theregister.com/2024/03/28/innovating_with_innersource/

**Comment by dellagustin-sap** [comment]
@CiaraFlanagan , if you still have space in this one, @michael-basil recently published the blog post https://community.sap.com/t5/open-source-blogs/innersource-first-contribution-explored/ba-p/13644916 - _InnerSource: First Contribution Explored_.

**Comment by CiaraFlanagan** [comment]
Git Hub resources page in Japanese

**Comment by CiaraFlanagan** [comment]
Yuki book?

**Comment by CiaraFlanagan** [comment]
> Hello @CiaraFlanagan , following the Community Call [Cross-Product Architecture - Lessons Learned from Applying Conway’s Law](https://bit.ly/ISCSAP), which was not recorded, we have published a blog post on the same topic: https://community.sap.com/t5/technology-blogs-by-sap/cross-product-architecture-embracing-conway-s-law-for-better-software/ba-p/13648600 Could you please add it to the newsletter?
> 
> Proposed text: Blog post from Guilherme Dellagustin based on the Community Call with Jochen Rode, on how SAP is applying InnerSource best practices at scale for collaborative work on architectural and technical topics. The described working mode resonates with several InnerSource Patterns, such as Dedicated Community Leader, Transparent Cross-Team Decision Making using RFCs and many others.
> 
> cc @OliveCannon

Hi @dellagustin-sap - that's added - I had to edit down some of your text for consistency with the other article links and resources.
