### ISSUE TITLE
Propose initial measures of success for the Marketing & Outreach Working Group

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#3]
Propose measures of success, with metrics to be tracked and indicative targets to show what success (and failure, where appropriate) would look like.

**Comment by claredillon** [comment]
First draft here: https://github.com/InnerSourceCommons/marketing-wg/blob/master/metrics.md

**Comment by lenucksi** [comment]
Dependent #10

**Comment by claredillon** [comment]
The document above includes all the suggestions of things we can measure. The second step was to consider goals for each one. However, suggest that it is not practical to discuss this outside the context of marketing budget for example, and also - there are a number of marketing projects taking higher priority right now (through which some more metric goals will be defined). 

Therefore propose we move this back to To Do for a later point in time.

**Comment by claredillon** [comment]
Moving back to ToDo and removing myself as assignee - we can come back to this at a later date.

**Comment by claredillon** [comment]
Metrics now reported on regularly.
