### ISSUE TITLE
Social Media Automation

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#30]
- Buffer
- Recurpost
- Other things?
-> Looks like Hootsuite is the winner here.

**Comment by spier** [comment]
@lenucksi I converted this note into an issue.

Do you have any proposed next steps here?

e.g. 
- set up a Hootsuite account
- give access to at least 2 ISC members
- setup the first scheduled messages (tweets, etc)

**Comment by spier** [comment]
* we want to be able for people from different timezones to post
* linkedin, twitter, youtube, facebook, ...
* centralized analytics reporting tool
* we need to get budget for this

**Comment by claredillon** [comment]
This issue is blocked until we get budget.

**Comment by spier** [comment]
Alright. Moving it back to the bottom of **ToDo** then.

**Comment by rrrutledge** [comment]
Is this needed?
