### ISSUE TITLE
Article on Galician translation of InnerSource patterns

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#300]

**Comment by CiaraFlanagan** [comment]
Interview template shared with Pablo Sanxiao. 

Next steps:

- Pablo to answer questions when he has the opportunity and time.
- Ciara to draft article and ask any follow up questions.
- Article to be shared in the newsletter.

**Comment by CiaraFlanagan** [comment]
Pablo has answered questions.

Next steps are to write a first draft.

**Comment by CiaraFlanagan** [comment]
Article shared in newsletter.

Next steps are:

- Check in w/ Pablo
- Create LinkedIn article
- Share on social

**Comment by rrrutledge** [comment]
Thank you for working on this.

**Comment by CiaraFlanagan** [comment]
Article shared in Newsletter.

Same version in LinkedIn article will be created week commencing May 20th.
