### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#31]
Having an issue template will help everybody that works on something new, to roughly provide the same type of information.

e.g. 
* what do you want to achieve? Why?
* how do you know then you are done?
* which blockers exist?
* which help do you need?

## Implementation notes

* GitHub offers built-in issue templates for this, so that users can more easily fill in the template
* We could model this roughly after how user story templates work

**Comment by spier** [comment]
## Title

A short summary of what you want to do. 

This will be the title of your issue that everybody sees first.

Example:
> InnerSource Commons 101 document for newcomers

## Purpose & Details

Description of what you want to do in more detail.
It is especially important that you describe the purpose here i.e. how will this contribute to the goals of the Marketing & Outreach working group?

Sometimes it can be helpful to describe things in the user story format, to make sure you understand who you are doing this for, and what the purpose is. A common user story format would be this:
“As a [persona], I [want to], [so that].”

Example:

> With the InnerSource Commons 101 document we want to give newcommers to the InnerSource Commons community a birds-eye view of our community, so that they have an easier time navigating it and figure out what is happening here, and how to get involved.

## Acceptance Criteria

How will we know that this is done?

Example:

> - We have produced a first InnerSource Commons 101 document (as a Google Doc).
> - We have shared the document with users that have joined in the last 2 months
> - We have added the doc to the #general channel, so that Newcomers can find it. (pinned / channel topic)

## Help Needed / Blockers

- Are there any dependencies to people outside of our Working Group? Where is help needed, or what could block progress on this?
- (if you already know that) How do you want to achieve consensus after finishing the issue? e.g. is lazy consensus in the WG enough, or do you need more than that?

**Comment by spier** [comment]
@dsugrobov here a first draft of how a template for new issues might look like. 

What do you think?
Anything we should add?

**Comment by voborgus** [comment]
Looks like something that can organize our cards. Seems we need advanced permissions on this repo to move it to [issue template](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository). 

I don`t have anything to add, let see it on practice.

**Comment by voborgus** [comment]
@claredillon can you convert this to issue template with the instruction above or to make me or @spier owner of this repo to be able to handle that, please?

**Comment by claredillon** [comment]
Dmitrii and Sebastian now both admins.

**Comment by spier** [comment]
Cool, thanks!

**Comment by spier** [comment]
Done.

How to use the template:

* click on [create a new issue](https://github.com/InnerSourceCommons/marketing-wg/issues/new/choose) 
* choose **Marketing & Outreach Issue**
* if you do that, you will see a template that you can fill in

Here an example of an issue that I created based on that template:
https://github.com/InnerSourceCommons/marketing-wg/issues/33

We can start with that and adapt it as we see fit.

**Comment by claredillon** [comment]
I think this looks great. Do you need anything else @spier to move this to "done"?

**Comment by spier** [comment]
Technically there is nothing else that we need, no.
I left it in Ready for Review so that I remember to demo it next week to the rest.

**Comment by spier** [comment]
Our last working group meeting didn't really happen. 
As this is a non-controversial change and everybody will immediately see the template when they create this issue, I am going for lazy consensus and consider this done.
