### ISSUE TITLE
Document how to add things to the newsletter

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceMarketing#311]
Zack Koppert expressed interest in this.

**Comment by zkoppert** [comment]
To add something to an upcoming newsletter, a community member can follow these steps.

1. Navigate to https://github.com/InnerSourceCommons/InnerSourceMarketing/issues?q=newsletter+in%3Atitle
![Image](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/6935431/4055500d-c394-42bb-8524-745ff7ca3b08)
2. Select which newsletter you want the update to go in
3. Scroll to the bottom of the page to the comment box 
![Image](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/6935431/b7965323-5632-4601-96c7-60e06a78f0a7)
4. Enter in your resource that you want to share and click the green comment box

**Comment by zkoppert** [comment]
cc/ @rrrutledge Is the above what you had in mind or something else? Is there somewhere I can store those instructions?

**Comment by rrrutledge** [comment]
I should have documented it in this issue.  Can you add it (via pull request) here?  Thank you‼️

https://github.com/InnerSourceCommons/foundation-governance/tree/master/how-to

**Comment by CiaraFlanagan** [comment]
Hi @zkoppert 

Thank you so much for doing this! It is much appreciated! 

Are you happy to add the MD file to https://github.com/InnerSourceCommons/foundation-governance/tree/master/how-to

Let me know if you don't have time and I'll sort it out.

**Comment by zkoppert** [comment]
I'll do that now, Thanks!

**Comment by zkoppert** [comment]
Here is the pull request: https://github.com/InnerSourceCommons/foundation-governance/pull/19
