### ISSUE TITLE
May 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#312]
We are preparing content for our May 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work

The deadline for submission is the end of the day: Tuesday, April 30

**Comment by CiaraFlanagan** [comment]
Article:
https://www.infoq.com/podcasts/documentation-innersource-practices-build-resilience/

**Comment by CiaraFlanagan** [comment]
News: 
New Book:  https://amzn.to/4cZ62L8

**Comment by CiaraFlanagan** [comment]
Video:
InnerSource - Open Source Ways of working within a Company
https://media.ccc.de/v/clt24-117-innersource-open-source-arbeitsweisen-im-unternehmen

**Comment by rrrutledge** [comment]
https://www.theregister.com/2024/04/08/a_culture_of_open_source/

**Comment by CiaraFlanagan** [comment]
Article:
https://www.getport.io/blog/how-libertex-group-is-continuously-improving-its-developer-experience-using-port?utm_content=286673737&utm_medium=social&utm_source=linkedin&hss_channel=lcp-81296713

**Comment by CiaraFlanagan** [comment]
Book: 
https://www.amazon.com/DevOps-Unleashed-Git-GitHub-collaborate-ebook/dp/B0CW189SNZ

**Comment by zkoppert** [comment]
Article:
https://www.shakebugs.com/blog/collaboration-in-software-development/

**Comment by CiaraFlanagan** [comment]
New Members announcement

**Comment by CiaraFlanagan** [comment]
New Board

**Comment by CiaraFlanagan** [comment]
Webinar: 
https://www.finos.org/blog/capital-ones-innersource-journey-roderick-randolph-and-arthur-maltson

**Comment by CiaraFlanagan** [comment]
> https://www.theregister.com/2024/04/08/a_culture_of_open_source/

Hey @rrrutledge - this is for a webinar in April.  We posted about the webinar in April and I haven't seen any videos ... Very happy to share any recordings in the future.
