### ISSUE TITLE
May US community call

### ISSUE THREAD

**Issue by OliveCannon** [InnerSourceCommons/InnerSourceMarketing#313]
https://docs.google.com/document/d/1h1X4NIV5-h8a50xTn-8abfUUiId8cbbm/edit?rtpof=true

**Comment by rrrutledge** [comment]
It this done?

**Comment by OliveCannon** [comment]
Hi Russ,
Yes, it is. I’m not right now so will update it tomorrow.
Thanks, Olive

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
