### ISSUE TITLE
June 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#317]
We are preparing content for our June 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work.

The deadline for submission: Monday, June 3.

**Comment by CiaraFlanagan** [comment]
Events: https://events.linuxfoundation.org/open-source-finance-forum-london/

**Comment by CiaraFlanagan** [comment]
Article:  to check against above article - same news:  https://www.fintechfutures.com/2024/05/lloyds-banking-group-collaborates-with-red-hat-to-adopt-modern-engineering-practices/

**Comment by CiaraFlanagan** [comment]
Article:  https://www.linkedin.com/pulse/revolutionizing-outsourcing-innersource-mishari-muqbil-tmy5c

**Comment by dellagustin-sap** [comment]
Hi @CiaraFlanagan , here is a video in Portuguese with community members from ITAÚ (https://en.wikipedia.org/wiki/Ita%C3%BA_Unibanco - largest banking institution in Brazil, as well as the [largest in Latin America](https://en.wikipedia.org/wiki/List_of_largest_banks_in_Latin_America)).

https://www.youtube.com/watch?v=YFEnvDBuzl4
I suggest it as content for the next newsletter.

**Comment by CiaraFlanagan** [comment]
Video: https://www.youtube.com/watch?v=YFEnvDBuzl4

**Comment by CiaraFlanagan** [comment]
> Hi @CiaraFlanagan , here is a video in Portuguese with community members from ITAÚ (https://en.wikipedia.org/wiki/Ita%C3%BA_Unibanco - largest banking institution in Brazil, as well as the [largest in Latin America](https://en.wikipedia.org/wiki/List_of_largest_banks_in_Latin_America)).
> 
> https://www.youtube.com/watch?v=YFEnvDBuzl4 I suggest it as content for the next newsletter.

Hey @dellagustin-sap 

I saw the video on the Brazilian community channel and added it when I saw it. Great minds think alike ;-)

**Comment by CiaraFlanagan** [comment]
News: Add Board Announcement

**Comment by coconux3** [comment]
Hello,

I had the pleasure to share with [TechRocks](https://www.tech.rocks/) community how to make DevOps supply chains reliable and secure. An opportunity to evaluate them, to detect technical debts and security vulnerabilities to help organizations make their chains robust and compliant 🔐 ✅

This podcast is a rich exchange with Philippe ENSARGUET, VP Software Engineering at ORANGE, around the current challenges of securing the software supply chain and how an InnerSource approach can be a catalyst.
https://www.tech.rocks/podcasts/c0f28539-4ad5-ee11-85f8-000d3aa9abc9/fiabiliser-et-securiser-les-chaines-d-approvisionnement-devops-aurelien-coget-r2devops-et-philippe-ensarguet-orange--s06ep04

Hope it will enrich your sharing.

**Comment by CiaraFlanagan** [comment]
Article: https://www.google.com/url?rct=j&sa=t&url=https://securityboulevard.com/2024/05/sonatype-lifecycle-best-practices-innersource/&ct=ga&cd=CAIyGjc4ZGNkNjVlMjVmMDk0MWM6Y29tOmVuOlVT&usg=AOvVaw2ARyUYtvoHn4mU8gj31ATt

**Comment by CiaraFlanagan** [comment]
Article: https://www.redhat.com/en/about/press-releases/red-hat-collaborates-lloyds-banking-group-boost-developer-experience-software-quality-and-speed-market

**Comment by CiaraFlanagan** [comment]
Video:  https://www.youtube.com/watch?v=LuTe1g0NaOo&list=PLbzoR-pLrL6qHuD538QsuJUw3eRuCfvgU&index=13

**Comment by CiaraFlanagan** [comment]
Article: https://lero.ie/opensourceinnersourcecrowdsourcing

**Comment by gselig1a** [comment]
Talk about InnerSource (content close to this one: https://www.youtube.com/watch?v=_lmAiOoQlhA) on 2nd July, at Azure Tech summer, France:
https://www.telecom-valley.fr/azurtechsummer/

**Comment by yuhattor** [comment]
The site for the Gathering is ready now:) 
https://gatherings.innersourcecommons.org/tokyo-2024/

**Comment by tfroment** [comment]
From the local French-speaking community: 
- a feedback on InnerSource at Amadeus will be presented by Gaël SELIG at the Azur Tech Summer - the conference of the TelecomValley association of Digital actors on the French Riviera - on July 2, 2024, at 2:00 PM, in Sophia Antipolis.
https://telecom-valley.fr/azurtechsummer
- Title: "how a small group of volunteers manages the CI/CD for over 1500 people thanks to InnerSource"
![image](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/62097390/e20cacb6-595b-4956-9aba-2b271d064905)

**Comment by afucher** [comment]
> > Hi @CiaraFlanagan , here is a video in Portuguese with community members from ITAÚ (https://en.wikipedia.org/wiki/Ita%C3%BA_Unibanco - largest banking institution in Brazil, as well as the [largest in Latin America](https://en.wikipedia.org/wiki/List_of_largest_banks_in_Latin_America)).
> > https://www.youtube.com/watch?v=YFEnvDBuzl4 I suggest it as content for the next newsletter.
> 
> Hey @dellagustin-sap
> 
> I saw the video on the Brazilian community channel and added it when I saw it. Great minds think alike ;-)

@CiaraFlanagan maybe with the video we can say that now we have a dedicated [page](https://github.com/InnerSourceCommons/awesome-innersource/blob/main/README.pt-br.md) in `awesome-innersource` to pt-br content?

**Comment by CiaraFlanagan** [comment]
CFP for Summit including a Save the Date

**Comment by CiaraFlanagan** [comment]
Save the date for Tokyo and European InnerSource Gatherings
