### ISSUE TITLE
July 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#318]
We are preparing content for our July 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work.

The deadline for submission: Monday, July 1st

**Comment by rmarting** [comment]
New initial pattern in the toolbox: Code of Conduct

https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/1-initial/code-of-conduct.md

**Comment by CiaraFlanagan** [comment]
> New initial pattern in the toolbox: Code of Conduct
> 
> https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/1-initial/code-of-conduct.md

Thanks @rmarting 

I'll frame this as a 'This Pattern Needs You' post in the newsletter.  Once again - thanks for the great pattern!

**Comment by anajsana** [comment]
Sharing the OSPO Survey info :) 


_The TODO Group and Linux Foundation Research, in partnership with Cisco, NGINX, Open Source Initiative, InnerSource Commons, and CHAOSS, are excited to be launching the 7th annual OSPO and Open Source Management survey!_

_Anyone involved in open source management, developing open source internal culture, establishing innersource best practices, part of ISPOs / OSPOs, etc, please take a few moments to fill out the survey: https://www.research.net/r/5GNDNPL_

_The survey closes in August 1st_

![osposurvey7 (1)](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/43671777/7d378c87-b0a8-488b-b6c4-a9376c9bd917)

**Comment by dellagustin-sap** [comment]
**SAP Announces its Open Source Manifesto**
Following the steps of companies like Mercedes-Benz, Porsche, Continental and Deutche Bahn, SAP has announced the publishing of its [Open Source Manifesto](https://github.com/SAP/open-source-manifesto) with the news article [SAP Commits to Expanding Open Source Innovation with New Open Source Manifesto](https://news.sap.com/2024/06/sap-commits-open-source-manifesto/). It is a statement of SAP's commitment and pledge to open source, aimed at customers, partners and the open source ecosystem in general, but also to its own employees. It reinforces the wish to continue to incorporate the culture and practices of open source inside the company, explicitly mentioning its encouragement to InnerSource. The manifesto is available as PDF through its new [open source landing page](https://www.sap.com/about/company/innovation/open-source.html), but also in Markdown format at a dedicated GitHub repository, https://github.com/SAP/open-source-manifesto. The announcement was also shared by SAP's Chief Technology Officer and Executive Board Member, Juergen Mueller on [LinkedIn](https://www.linkedin.com/posts/juergmueller_sap-open-source-activity-7211686189999812609-BBYC).

References:
- Announcement - https://news.sap.com/2024/06/sap-commits-open-source-manifesto/
- The Manifesto on GitHub - https://github.com/SAP/open-source-manifesto
- Social Media Posts (by SAP and SAP members)
    - [SAP News LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7211688825230688256)
    - [SAP News Twitter/X](https://x.com/SAPNews/status/1805922597802016782) 
    - [SAP Open Source Twitter/X](https://x.com/sapopensource/status/1805918934740152333) (Quote tweet from SAP Open Source)
    - Juergen Mueller (Chief Technology Officer and Executive Board Member at SAP SE) - [LinkedIn](https://www.linkedin.com/posts/juergmueller_sap-open-source-activity-7211686189999812609-BBYC)
    - @mameling (Executive Vice President and Chief Product Officer, BTP Foundation & ADAI, MD SAP Labs Dresden) - [LinkedIn](https://www.linkedin.com/posts/michael-ameling_opensource-openui5-openjdk-activity-7211677468150112256-yopr)
    - @peter-giese - (Head of SAP OSPO) [LinkedIn](https://www.linkedin.com/posts/peter-giese_opensource-sapopensource-opensourcemanifesto-activity-7211688461777432577-dPng)

**Comment by CiaraFlanagan** [comment]
Article:  https://bearman.nl/2024/06/20/open-inner-protected-source/

**Comment by CiaraFlanagan** [comment]
Blog: https://bitergia.com/blog/bitergia-analytics/speeding-up-your-innersource-development-embrace-visibility-to-drive-velocity/

**Comment by CiaraFlanagan** [comment]
Headline:  CFP

**Comment by CiaraFlanagan** [comment]
Waiting on Olive for link to ABC August Community Call

**Comment by CiaraFlanagan** [comment]
Article: https://bearman.nl/2024/06/20/open-inner-protected-source/

**Comment by CiaraFlanagan** [comment]
> New initial pattern in the toolbox: Code of Conduct
> 
> https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/1-initial/code-of-conduct.md

Hey @rmarting and @spier 

I have a quick question for you both:  

I've noted that there are now 3 known instances for the pattern.  Does this make it a mature pattern or would you like me to still invite contributions in tomorrow's newsletter?
