### ISSUE TITLE
August 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#319]
We are preparing content for our August 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work.

The deadline for submission: Monday July 29th

**Comment by CiaraFlanagan** [comment]
Add Lenstra as sponsor

**Comment by MaineC** [comment]
Add information about new initial stage pattern about cross team retrospectives. Call for action could be asking readers to add themselves if they have seen the pattern in the wild so we can move it over the initial stage line: 

https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns%2F1-initial%2Fcross-team-retrospectives.md

**Comment by CiaraFlanagan** [comment]
New sponsor announcement

**Comment by CiaraFlanagan** [comment]
New Community Manager role

**Comment by CiaraFlanagan** [comment]
More about the Summit and Gathering pages

**Comment by CiaraFlanagan** [comment]
resources noted .
