### ISSUE TITLE
Set up event registration. 

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#32]
We can no longer use BrownPaperTickets. 
We need to agreed which tool we use to capture event registration details. 
Then we need to set up the event in the tool.
We'll know we're done when we have captured test registrations.

**Comment by claredillon** [comment]
Test site in EventYay here. https://eventyay.com/e/c169a0dd

- Not using for agenda - doing that on innnersourecommons.org

Next steps 

- [ ] agree that this is right platform to use.

- [ ] get details of a bank/paypal account so we can set up the option for paid tickets. 

Check:

- [ ] Tagline for event

- [ ] Graphic Designer help needed/available?

- [ ] 1 ticket per person

- [ ] Confirm cost

**Comment by claredillon** [comment]
EventYay seems to be sufficient for our needs. @mishari has also had experience using it from Asia. Likely our choice. We are waiting on the bank account/Paypal details to finish this card. 

Note we have agreed target date for setting registration live will be week of Aug 10th. 

In relation to other check above: 

- Confirmed we can allow bulk purchase of up to 10 tickets (corporations have expressed need for this before)

Will create separate cards:
- to confirm cost (and charges). 
- to explore potential event taglines
- to create an ask for a graphic designer.

**Comment by claredillon** [comment]
Because of on-going delays to getting the ISC account, we decided to go with Danese's paypal account as a fall back. 

However, there have been some problems with [EventYay set up](https://eventyay.com/e/8ccaf0b0) :

1. Danese and others reported issues in unclear path to purchase tickets. This has logged as issue with [EventYay here](https://github.com/fossasia/open-event-frontend/issues/4777) and is being worked on. 

2. I experienced issues after paying for my ticket via Paypal - after filling in the details (logging in through PayPal) - it wouldn't accept my payment. 

3. Using Paypal brings up its own issues - as the receipt from Paypal does not reference the event at all, see screen shot below (created through the EventBrite system/PayPal option, but assuming same process for EventYay). EventBrite get around this limitation by processing payment through EventBrite site - which handles receipts etc. that reference the summit. 

4. Some crashing / timeouts when creating the event and loading images.

Therefore trying EventBrite as alternative.

**Comment by claredillon** [comment]
[Registration link for ISC Fall Summit on EventBrite](https://www.eventbrite.ie/e/innersource-commons-fall-2020-virtual-summit-tickets-117435975163).

Notes:

- Tried using Danese's paypal first caused issue in that the receipt only lists Danese's personal details, not mention of the event. 

![image](https://user-images.githubusercontent.com/32961070/90628852-3d127880-e216-11ea-97f5-fe13c9677a89.png)

**Comment by claredillon** [comment]
Second attempt at the EventBrite was to use EventBrite's own payment system and that produced a much better experience. New receipt experience below. 

Event Link [here](https://www.eventbrite.ie/e/innersource-commons-fall-2020-virtual-summit-tickets-117435975163): 

![image](https://user-images.githubusercontent.com/32961070/90629051-95e21100-e216-11ea-8583-df8e83362763.png)

**Comment by claredillon** [comment]
Updated to include @dsugrobov new beautiful graphic.

**Comment by claredillon** [comment]
Having worked through both - my recommendation is that we should go with EventBrite for the default ticket platform for the Fall Summit and work with EventYay to help them resolve the issues we experienced above, and hopefully use them next time. 

Here are my reasons for proposing we go with EventBrite:
- A easier to use, no glitch process, familiar to more people. 
- The graphics/design looks better.
- Option to have EventBrite manage the payments, which gives a better experience as the receipts don't reference Danese's personal accounts. 
- We don't have spare time/resources to manage bug fixing of the ticketing platform while trying to finalise the summit. 

Propose we make final decision at the Summit planning session later today.

**Comment by lenucksi** [comment]
Just as a side-note: EventBrite reserves free admission to every event you are hosting through them if I understood correctly - which should not be a problem in our case though right now.
We've repeatedly been offered direct help from Hong Phuc regarding EventYay should we need anything, just let me know.

**Comment by claredillon** [comment]
Thanks Johannes - I didn't experience that restriction when setting the event up (no automatic free option) - but will keep a close eye on it. 

To update from our discussion right now in the planning meeting - we have agreed to move ahead with EventBrite for this time round on the basis of the points above - but we have also agreed to work with EventYay to iron out the issues we have experienced in time for the Asian summit. We will also have an ISC account by that time, and should therefore not experience the receipt issue either. 

For reference: Danese, Dmitrii and Brittany all agreed with this approach. 

@lenucksi it would be wonderful if Hong Phuc could help us work through this - as we'll be stretched to get the issues documented in the next few weeks otherwise.

**Comment by claredillon** [comment]
Last note is that we can have multiple admins for the EventBrite event page - so making a call for others to send me their email address used for EventBrite log-in.
