### ISSUE TITLE
September 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#325]
We are preparing content for our September 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work.

The deadline for submission: TBC

**Comment by spriya-m** [comment]
New pattern added - [InnerSource Hackathon](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/1-initial/innersource-hackathon.md).

**Comment by CiaraFlanagan** [comment]
https://thenewstack.io/how-to-implement-innersource-with-an-internal-developer-portal/

**Comment by tfroment** [comment]
Here is a suggestion announcing our first FR Local chapter community meetup, September 20th:

The Francophone Chapter of InnerSource Commons was founded in early 2023 with the initial goal of making InnerSource resources more accessible to French-speaking communities. Our first significant achievement was translating the InnerSource Commons website into French, now available at [innersourcecommons.org/fr](https://innersourcecommons.org/fr). Following this, we recorded our first webinar, which can be viewed on our YouTube channel: [InnerSource Commons Francophonie](https://www.youtube.com/@innersourcecommonsfrancophonie).

Eighteen months later, our community is thriving, and we are excited to announce our next gathering on **September 20th at 3:00 PM CEST**. With 13 participants already registered, this meeting is open to all French-speaking individuals interested in InnerSource. During this session, we will discuss the organization of our first InnerSource gathering.

Our Slack community has also grown, with over 50 members in the #fr-general channel. We encourage you to join us on Slack at https://innersourcecommons.slack.com/archives/C04HJ3KPR19, where you can request an invitation to the upcoming meetup and engage with other members of the community.

We look forward to seeing you there and continuing to build a strong Francophone InnerSource community together!

Could be illustrated by 
![image](https://github.com/user-attachments/assets/15fcee1e-a69e-4fb1-91b9-5dfce476c739)
or 
![image](https://github.com/user-attachments/assets/177a247d-cb44-4363-9df9-805e22563167)

or even this one (in french :-)) 
![image](https://github.com/user-attachments/assets/56b572be-26d0-4986-82ac-bf49a9f982c5)

**Comment by rrrutledge** [comment]
https://innersourcecommons.slack.com/archives/C04PXKRN4/p1725417083694819
