### ISSUE TITLE
October 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#326]
We are preparing content for our October 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work.

The deadline for submission: TBC

**Comment by CiaraFlanagan** [comment]
check and see if we've posted this before: https://www.publicissapient.com/insights/decoding-organizational-agility-with-innersource (I think we have)

**Comment by reginankenchor** [comment]
An article on a Guide to InnerSource Patterns: (https://www.linkedin.com/pulse/guide-innersource-patterns-regina-nkenchor-njlbf/)

**Comment by CiaraFlanagan** [comment]
@tanzhongyi003 article

https://www.linkedin.com/pulse/collaborative-innovation-leads-future-comprehensive-analysis-%E4%B8%AD%E6%84%8F-%E8%B0%AD-riwac/?trackingId=8poS44QugB0aE8x3ONpEWg%3D%3D

**Comment by CiaraFlanagan** [comment]
@tfroment - adding your talk to the October newsletter: https://www.opensource-experience.com/en/program/speakers/

**Comment by CiaraFlanagan** [comment]
Start of African Local Community

@reginankenchor - if there's anything you would like me to add for this news item, please let me know!

**Comment by rrrutledge** [comment]
https://www.linkedin.com/posts/activity-7246836462866821122-HJ9b?utm_source=share&utm_medium=member_desktop

**Comment by CiaraFlanagan** [comment]
State of InnerSource report

**Comment by reginankenchor** [comment]
> Start of African Local Community
> 
> @reginankenchor - if there's anything you would like me to add for this news item, please let me know!

Hi @CiaraFlanagan , when are you planning to publish the newsletter? I will have my updates ready by tomorrow. Is that too late?

Not too late @reginankenchor - I'm hoping to publish about 3pm - 5pm tomorrow BST

**Comment by reginankenchor** [comment]
Hi @CiaraFlanagan , when are you planning to publish the newsletter? I will have my updates ready by tomorrow. Is that too late?

**Comment by reginankenchor** [comment]
> > Start of African Local Community
> > @reginankenchor - if there's anything you would like me to add for this news item, please let me know!
> 
> Hi @CiaraFlanagan , when are you planning to publish the newsletter? I will have my updates ready by tomorrow. Is that too late?
> 
> Not too late @reginankenchor - I'm hoping to publish about 3pm - 5pm tomorrow BST

Hi @CiaraFlanagan  Here are the initial information we might need for now. I've updated the repositories, and we still need a banner. I was wondering if we could get a template to edit. We can discuss that further next week when you have some free time. In the meantime, this information should suffice:
    Africa Repository: https://github.com/InnerSourceCommons/africa
    Slack: Join our channel #africa at https://innersourcecommons.slack.com/archives/C07MXDSG2P8.
    Twitter: Follow us at @InnerSourceAF https://x.com/InnerSourceAF.
    LinkedIn: Connect with us at InnerSource Commons Community Africa https://www.linkedin.com/company/innersourceafrica.

**Comment by CiaraFlanagan** [comment]
Tokyo Gathering Returns!

**Comment by CiaraFlanagan** [comment]
InnerSource Summit

**Comment by CiaraFlanagan** [comment]
Hero of the month

**Comment by tfroment** [comment]
FR Community Meetup (Sept 20th), scheduling the first ISC french gathering on Dec 5th in Paris (France)
