### ISSUE TITLE
November 2024 Newsletter

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/InnerSourceMarketing#327]
We are preparing content for our November 2024 Newsletter.

Please share your suggestions for content. This can include:

- News about your InnerSource project!
- Any news about activities happening in the wider InnerSource community
- Favorite InnerSource articles, videos or resources you have come across over the past month.
- Learning Path updates
- Pattern of the month
- Our heroes of the month - any members that you wish to recognize for their great work.

The deadline for submission: November 5

**Comment by CiaraFlanagan** [comment]
@claredillon podcast: https://lnkd.in/gWT_afDn

**Comment by CiaraFlanagan** [comment]
https://www.google.com/url?rct=j&sa=t&url=https://resources.github.com/topics/innersource/%3Ftype%3Darticle&ct=ga&cd=CAIyGjc4ZGNkNjVlMjVmMDk0MWM6Y29tOmVuOlVT&usg=AOvVaw3771-seUSRheIrCUMsPztU

**Comment by CiaraFlanagan** [comment]
https://www.google.com/url?rct=j&sa=t&url=https://thenewstack.io/how-to-implement-innersource-with-an-internal-developer-portal/&ct=ga&cd=CAIyGjc4ZGNkNjVlMjVmMDk0MWM6Y29tOmVuOlVT&usg=AOvVaw1P2hL2nfOQmmxMxQ87texe

**Comment by rrrutledge** [comment]
https://www.youtube.com/watch?v=oICAoClkL7U&list=PLmPXh6nBuhJsLdVouWRmB6q9WKnjNdxyL&index=54

**Comment by CiaraFlanagan** [comment]
https://www.youtube.com/watch?v=oICAoClkL7U&amp;index=54

**Comment by ribeiroe** [comment]
Hi Ciara,

Thank you for your feedback. As we agreed, I’m including the link to my article here.

[ribeiroe](https://www.linkedin.com/pulse/unlocking-innovation-innersource-why-organisations-should-ribeiro-jl7ef/?trackingId=Dc4fQOhtTvy%2FamO5sskuLg%3D%3D)

Please let me know if you need any additional information.

Thanks, and have a lovely weekend,
Eduardo

**Comment by rrrutledge** [comment]
https://engineering.indeedblog.com/blog/2024/08/indeed-gitlab-ci-migration/

**Comment by CiaraFlanagan** [comment]
PT-BR version of State of InnerSource now available ...

**Comment by CiaraFlanagan** [comment]
@tfroment is speaking here about InnerSource Patterns:   https://www.opensource-experience.com/en/program/speakers/

**Comment by CiaraFlanagan** [comment]
@tfroment - do you want us to add anything about the Paris Gathering in this month's newsletter?

**Comment by rrrutledge** [comment]
[Fostering Open Source Culture](https://www.amazon.com/Fostering-Open-Source-Culture-Innovation/dp/B0DFGB42SM) book hits pre-order.  With a section on InnerSource authored by numerous participants in the InnerSource Commons.
