### ISSUE TITLE
Add ISC to the "Inner Source" wikipedia page

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#33]
## Title

Add a link to the InnerSource Commons on the ["Inner Source" wikipedia page](https://en.wikipedia.org/wiki/Inner_Source)

## Purpose & Details

When @mishari shared the link to the ["Inner Source" wikipedia page](https://en.wikipedia.org/wiki/Inner_Source), I noticed two things:
a) it is spelled "Inner Source" there, rather than "InnerSource"
b) the wiki page does not mention the InnerSource Commons or link back to http://innersourcecommons.org

In this issue I only want to work on (b), with the following purposes:

- so that we can explain how the ISC supports InnerSource (i.e. we share the fact that the ISC is a non-profit org supporting InnerSource
- we learn how to edit the wiki page, and go through the wikipedia review process, so that we know how to do that in the future

In user story format I might write:
As a reader on wikipedia, I would like to know if there is any organization that is supporting the idea of InnerSource, so that I know where to get further information.

## Acceptance Criteria

- the ["Inner Source" wikipedia page](https://en.wikipedia.org/wiki/Inner_Source) mentions the InnerSource Commons and links to http://innersourcecommons.org

## Help Needed / Blockers

- scope creep: trying reword "Inner Source" to "InnerSource" would be way too much work I suspect i.e. I would not want to try this at the moment

**Comment by spier** [comment]
Useful info to add to wikipedia would be:

- full legal name of the foundation
- some info from the incorporation http://innersourcecommons.org/news/2020-02-19-press-isc-incorporation/
- mission statement of the foundation
- link to http://innersourcecommons.org

I think this would be good enough to get us started already.

**Comment by lenucksi** [comment]
Good points. 
I found a [German page](https://de.wikipedia.org/wiki/Inner_Source) and an [English language](https://en.wikipedia.org/wiki/Inner_Source) page.

Both of those are mostly shepherded by our German academics and likely @user-group.
For the German one we'll have to deal with the local Blockwarts which will likely be more than allergic against everything that could be understood as marketing / advertising.

The likelyhood of getting the camelcased version into the page title is somewhat close to zero, as this has been a battleground on both pages with repeated change in the past and the space-version being prefered by one of the main authors.

Do we know about anyone who can say something on the current rules regarding corporate / foundation edits?

**Comment by rrrutledge** [comment]
This sounds like a good idea.  @spier do you want to take a crack at it?

**Comment by rrrutledge** [comment]
I did it.  Feel free to edit!

**Comment by spier** [comment]
And it was immediately reverted by somebody :(

![Screenshot 2023-12-05 at 08 45 22](https://github.com/InnerSourceCommons/InnerSourceMarketing/assets/163029/beea068b-27c6-403f-b4ae-f6f74dd8f1e1)

**Comment by rrrutledge** [comment]
Here's some more information about the revert: https://en.wikipedia.org/wiki/User_talk:Rrrutledge?markasread=298712582&markasreadwiki=enwiki#c-Materialscientist-20231204233500-December_2023
