### ISSUE TITLE
Open CFP

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#34]
Open Call for Presentations. 
Create Form for CFP

**Comment by claredillon** [comment]
@dicortazar created a Google form here (same as last summit): https://docs.google.com/forms/d/e/1FAIpQLScIcPEotrClmqLYaiFv-rGei6R2r8jbP2a-oPrC8NSWA0dEmQ/viewform

However, if we use EventYay - it seems they include a speaker management CFP area, which could be used instead and be helpful in managing submissions. Need to decide best approach.

**Comment by dicortazar** [comment]
The agreement here was to proceed with the current website and this is and Google Forms.
This form is already ready to go at https://docs.google.com/forms/d/1x-aXSZBT6pd5QwNeYvdqKm0KoOohYwWvF2ATkrUNfww/edit

Moving this to done
