### ISSUE TITLE
Take down innersourcecommons.net

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceMarketing#357]
It is confusing and not being used.  We should take it down.

**Comment by andrea-kyurchiev** [comment]
@rrrutledge We can redirect the domain and stop the auto renewal so the domain can expire. Not sure where innersourcecommons.net  is hosted, whoever has access to that would be able to take it down

**Comment by rrrutledge** [comment]
First, of all, @andrea-kyurchiev - thank you for monitoring GitHub and responding to things you see here right away.  That is great!

**Comment by rrrutledge** [comment]
Second - if the domain is redirected and expires, who cares if some random server at some random IP address is still serving it up.

Do I understand that right?

**Comment by andrea-kyurchiev** [comment]
Well, it could essentially incur charges as the hosting would continue (assuming it isn't hosted for free somewhere?) Other than that yes it'll just be hosting with nothing really leading to it other than an arbitrary IP address

**Comment by rrrutledge** [comment]
No problem.  To my knowledge we are not paying for any hosting, so it is either free or someone else paying for it.

Please implement your plan.  Sounds great!

**Comment by andrea-kyurchiev** [comment]
That should be it. Could take a couple hours to propagate

**Comment by andrea-kyurchiev** [comment]
Closing this at that seems to be redirecting now

**Comment by rrrutledge** [comment]
Thank you!

https://www.innersourcecommons.net/ redirecting, but https://innersourcecommons.net/ not redirecting.
