### ISSUE TITLE
Create ISC Fall Summit Webpage

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#36]
Create the ISC Fall Summit Webpage, using Spring summit early version as template. Include CFP.

**Comment by claredillon** [comment]
First draft completed here: https://github.com/InnerSourceCommons/innersourcecommons.org/pull/182. Just need to add the CFP link.

**Comment by dicortazar** [comment]
Info was slightly updated and merged (bad practice here as I merged myself... sorry about this, but I tried to comply with yesterday's decision about having this live as soon as possible).

I need now to work on the links from the main website to this page so info is updated consistently across the website.

**Comment by dicortazar** [comment]
PR in process. https://github.com/InnerSourceCommons/innersourcecommons.org/pull/183

**Comment by claredillon** [comment]
All done now: http://innersourcecommons.org/events/isc-fall-2020/ and linked from homepage.
