### ISSUE TITLE
Apply for FOSS Responders fund to allow us to fulfill Summit Tshirt commitment.

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#4]
Brown Paper Tickets appears to be insolvent, so we cannot redeem the ticket fees people paid for ISC Online Spring Summit 2020. FOSS Responders have indicated we would qualify for reimbursement from their fund. We need to apply. Recommend we apply for c. 1350-1500 EUR to cover Tshirts for attendees and speakers and charity donations (which people could choose instead of Tshirt).

**Comment by dicortazar** [comment]
Hey, thanks for creating the ticket. 

I just submitted the proposal to the FOSS Responders. We have been assigned the unique id 36 for further communications with them.

The final financial aid is about $1530.

**Comment by lenucksi** [comment]
This is still waiting for feedback from the fund.

**Comment by dicortazar** [comment]
Update: FOSS Responders apologize for the delay with this and they kindly ask for an extra delay till mid-August.

**Comment by dicortazar** [comment]
Just received a confirmation from the FOSS Responders team that we're in.

We have now to send an invoice to them with up to $2K. Our initial budget estimation was about 1530$ approx. I suggest we keep with our original budget estimation that will cover t-shirts a small gift to speakers as far as I remember.

I copy the email here:


> Daniel,
> 
> I'm following up regarding your request for financial assistance from FOSS Responders. Thanks for bearing with us while we've worked through the processes on our end.
> 
> The FOSS Responders team has reviewed your request for support, and I'm pleased to say that we'll be able to provide a grant to help lessen the financial impact from moving the InnerSource Commons Spring Summit online.
> 
> The best way to receive the grant is to submit an invoice/expense for no more than $2,000 to the FOSS Responders Open Collective: https://opencollective.com/foss-responders
> 
> You can find instructions for submitting an invoice here – https://rb.gy/oxkive
> 
> If you have any questions or hiccups, please let us know.
> 
> All the best,
> -Duane
>

**Comment by dicortazar** [comment]
I move this ticket to Review as the next step is to send such invoice. Given the current bank account situation, I'm not sure how to proceed or if we can even send such invoice.

**Comment by claredillon** [comment]
Good plan @dicortazar - as soon as we get account, we can send invoice.

**Comment by dicortazar** [comment]
Bank account is ready to go, @cewilliams has been updated with last details, and we have an updated OK from the FOSS Responders team.

Next step: @cewilliams fill the invoice following the process stated at https://rb.gy/oxkive .

**Comment by claredillon** [comment]
Complete and funds received back in 2020! T shirts (finally) were distributed in Dec 2020. Thanks to all for the work on this.
