### ISSUE TITLE
Notify people about their charity donation after ISC Spring Summit 2020

### ISSUE THREAD

**Issue by dicortazar** [InnerSourceCommons/InnerSourceMarketing#41]
### Purpose & Details

A certain number of people asked to donate to charity their ticket fee after attending the event. Due to the COVID situation and BrownPaperTickets financial status, we have not received any fee yet.

List of people available at https://docs.google.com/spreadsheets/d/1GMopppxGLgqfmX-EHrjsSlBjmUHMqivPBx8ugwdL8SM/edit#gid=1892272642
Email proposal to be done

### Acceptance Criteria

Send emails

**Comment by clcoffey** [comment]
Is this issue still relevant or should it be closed?

**Comment by claredillon** [comment]
We let the community know at the time that we never received funds from Brown Paper Tickets. CLosing this
