### ISSUE TITLE
Decide whether to make the Marketing WG project board public

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#43]
A short summary of what you want to do. 

It was suggested on the marketing channel that we should make the marketing project board public to 
1. aid on-boarding (so no access needs to be assigned)
2. be more transparent

This card is to track the discussion and call for final vote. 

Acceptance Criteria. We will know when it's done when we have a decision.

**Comment by claredillon** [comment]
In discussion at the Marketing WG Meeting on the 6th of July, we brought up this discussion. 

Note that the marketing board is currently Private. 

Points made then and afterwards to consider:
- Most of the cards require insider knowledge to understand or contribute - therefore, there is little chance a complete outsider will happen along and be able to contribute in a meaningful way.
- Some cards are pointing to GDrive docs that contain minutes of meetings that are under Chatham House Rules.
- Some cards refer to discussions that are not suitable for the public domain (e.g. criteria for choosing summit speakers)
- We can always work around the access issue by making sure to check people are given access at the start of meetings and highlighting that necessity in the Slack channel.

Therefore - I propose we do not make the board public at this time.

Next action is to bring this to the next WG meeting to confirm this course of action (which is to do nothing with the current set up at this time).

**Comment by spier** [comment]
I agree, making this public does not help us right now.
