### ISSUE TITLE
Create a Style Guide

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#44]
We need to be more consistent across all ISC channels and promotions. Call is to agree and docuement a consistent style guide that will cover at least guidelines on which of the following we use in given scenarios.:

1. Fonts (preferred fonts for different scenarios)
2. Logos
3. Background images
and where appropriate:
3. Notes on tone

Document should contain examples and links to assets where appropriate.

This will help everyone create new assets more easily.

How will we know that this is done?
Document created and reviewed by at least 2 members of the Marketing WG.

**Comment by claredillon** [comment]
Please choose a font that is available in Google and Microsoft font sets to allow for maximum accessibility and tool usage in creating docs/assets.

**Comment by lenucksi** [comment]
Good ticket, here are few suggestions:

Fonts:
- We should divide between Print and Web. 
- Web usage will restrict us to [Web-Fonts](https://en.wikipedia.org/wiki/Web_typography) and will need a graceful deterioration hierarchy
- Print will allow us to use any font that we want, i.e. anything that is available in OTF/TTF format. There are many [openly / freely licensed fonts](https://de.wikipedia.org/wiki/SIL_Open_Font_License) that we can choose from. We should store the font files in our repository. Ideally we choose a font that is also present in the [Google Web font directory](https://fonts.google.com/).
- If we are looking to use this in other places than just the marketing WG "Google and Microsoft" in not sufficient, but Linux needs to be taken into account too. Once we adhere to what is written above this should be doable.
- Also, when choosing a font we need to make sure that it contains glyphs for our most likely scripts: Latin, full western spectrum (diacritics), Cyrillic, Chinese, Japanese, Sanskrit, ...

Logos:
- Ideally we need a vector version and a raster version, where the vector version is the upstream. SVG, LibreOffice Draw/Open Document Format, PNG, JPG should help here
- Lets use this Git repository to store them.
- We already have some of this IP in our website repo that we can move over here.
- We should, e.g. by putting a small text file with the same file next to the file, put licensing and attribution information next to all visual / logo assets and ensure that this is part of the process of adding new assets, e.g. by means of a small checklist-text-file in the parent directory.

Notes on tone: 
- There's actually software geared at marketing use to automate checking for this. However, it's a bit of a mess to integrate so a nice textual checklist should do. 
- Let's also place this in our repo. 

This will facilitate integration into other parts and references.

**Comment by claredillon** [comment]
Suggestions from WG meeting 17/08 - let's create a list or "lookbook" of what we want to look like.

**Comment by claredillon** [comment]
Idea is to ask the ISC Community for suggestions. Dmitrii to look at the appropriate question to ask.

**Comment by spier** [comment]
@claredillon don't take this as disagreement, but just as a question:

> We need to be more consistent across all ISC channels and promotions.

Some questions:

* Why do we need to be more consistent?
* What is the worst thing that can happen when we are not consistent in these things? (we should be able to show the effects based on the assets that we have today)

With these questions as I starting point I hope we can describe the purpose of this activity more clearly, and with that decide on useful increments towards that goal.

**Comment by spier** [comment]
## Why?

- efficiency (people don't want to make the decision themselves)
- e.g. if I want to present the InnerSource Community at my own company, what assets can I use?
- if people want to speak "on behalf of the ISC". how do they know that they are doing it "correctly"?
- tone - we don't want to be too formal (we are a community, not a company)

## Good things to have

- consistent enough but not too much (e.g. the swirl on the youtube channel should at least be the right way around :))
- template for slides

**Comment by voborgus** [comment]
Started to work on this [here](https://docs.google.com/document/d/1SyG66_00faqPA9c4hcO0QFXzDLi1IoL-Q_V9XPUox4k/edit#).

**Comment by dicortazar** [comment]
Agreed during the call that this is done. We may open others.

**Comment by spier** [comment]
Closing this issue, to make it even more clear that it is done :)
