### ISSUE TITLE
Set up Mailchimp for ISC

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#45]
Create a Mailchimp account for ISC newsletter. 

1. Set up a test Mailchimp newsletter account, with Marketing WG as members to test functionality.
2. Make sure there is a way to easiy subscribe and un-subscribe.
3. Add all those who have already indicated they want to sign up to newsletter

@dicortazar has some from an early ask.
@claredillon has more from the Spring 2020 Summit feedback form. 

How will we know that this is done?

Stage 1: 2+ members of Marketing WG have received first newsletter; 1 has successfully automatically un-subscribed and second test newsletter sent to confirm.
Stage 2: All those who have asked to be signed up have been added.

**Comment by claredillon** [comment]
We've set up an account here. And have tested initial newsletter successfully (subscribe/unsubscribe etc). This week, Cedric has created a new alias news@innersourceorg.com which we can use to send newsletters. Will complete this action week of Aug 10th.

**Comment by lenucksi** [comment]
Where do we store our how-to 
- get access, has access
- operate
- ...

information and who would write that up?
How about just creating a small doc in the repo here we could link to from the front page of the repo?

**Comment by claredillon** [comment]
Good idea @lenucksi . 
Didn't get to complete the test last week - but will this week. And will include this as part of the doc outlining [how we communicate](https://docs.google.com/document/d/1EaJVI7qcvU_B2nND7PJklEEdopRFU-SC_MlsosTHPRg/edit?usp=sharing).

**Comment by claredillon** [comment]
Done. We have mailed everyone who signed up to newsletter to promote summit.
