### ISSUE TITLE
Confirm ticket cost and charges

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#47]
Outline summit ticket cost. Clarify charges from payment engines (e.g. Paypal and EventYay).

**Comment by claredillon** [comment]
Discussions so far :
Proposed $30 cost for participants. This should include all payments (event engine and Paypal if necessary), but ex.VAT.

Next task is to determine EventYay costs. 

EventYay pricing pages giving a 404. https://support.eventyay.com/pricing .

If anyone knows how we can get this info - help would be appreciated. Destination account will be US Paypal. 

For reference. [Eventbrite's own payment engine](https://www.eventbrite.ie/support/articles/en_US/Troubleshooting/how-much-does-it-cost-for-organizers-to-use-eventbrite?lg=en_IE) charges (for US domestic sales) fees of 2% + $0.79 per ticket sale.

**Comment by voborgus** [comment]
Opened an issue in their repo: https://github.com/fossasia/support.eventyay.com/issues/52
Looks like the support portal is under active construction.

**Comment by lenucksi** [comment]
We've got the following information from Hong Phuc who is involved with EventYay:
- If you sell tickets, there is a 2% fee on the income of your PAID tickets, an invoice will be sent to you at the end of the event.
- We can self-host or use the hosted version (likely we'll end up with the latter) 
- Hong Phuc offered us help setting it up if we need it.
