### ISSUE TITLE
Create InnerSource Message House

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#51]
Create InnerSource Message House to agree on key messages on why people should do InnerSource.

**Comment by claredillon** [comment]
This has been completed here: https://docs.google.com/document/d/18rIRzXVh6-ly75BjIyYyEc1o6Kbf_dB_xaJcVSew0TQ/edit?usp=sharing

This has also been shared in Marketing WG. 

Leaving this open to share progress in the next Marketing WG. We plan to make next review of this post Fall Summit. People can contribute and comment in the meantime.

**Comment by lenucksi** [comment]
There's a bunch of research results from academia on this topic and the possible limitations. We should probably incorporate those, at least the limits. @user-group and @maxcapraro might be interested.
