### ISSUE TITLE
Guidelines for Speaker Choice

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#52]
Outline the guidelines and principles we can use to decide final speaker lineup

**Comment by claredillon** [comment]
From discussions so far:

Speaker line-up for the Fall 2020 Summit (America) should be considered in the light of:

- **Diverse representation**: We should have a diverse set of speakers. For example in the context of gender diversity, we should aim for _at least_ 25% female speakers at both keynote and speaker level. 

- **Geographical representation**: Because the ISC Fall summit is traditionally the US summit, there is likely a skew towards US/American speakers. However, we should also have representation from the rest of the world. 

- **Size of org**: Ideally we would have a balance between speakers from large and small companies to reflect the ISC community.

- **Type of org**: Ideally we would have a balance between the types of organizations (e.g. a mix across industry verticals).

- **Different Roles**: We discuss different roles in InnerSource, should we consider representing points of views from different groups?

**Comment by claredillon** [comment]
**Themes**
In relation to the mix of topics, here are some  additional considerations:

**Level of Experience**: Ideally there would be a mix of topics or themes reflecting different levels of InnerSource Experience. E.g. a talk from someone with tips on getting started, and a talk from someone who has been practising for some time and looking to scale or optimize their practice. 

**Different Challenges**
InnerSource practitioners face different challenges, ideally the topics in the summit would cover a broad number of these challenges, for example:

- How to convince stakeholders
- How to get started
- How to scale
- Tools to use
- InnerSource Culture
- InnerSource Patterns
- Metrics for InnerSource
- Community Building Tips
- How to engage with the ISC
- Global Trends in InnerSource

**Key Messages**
In addition to exploring the challenges IS practitioners face, there are some key messages we would like to create a body of evidence for, that would help in spreading the word about InnerSource, for example:



- InnerSource breaks down silos and helps increase cross-company collaboration
- InnerSource builds necessary/optimal developer skills
- InnerSource is a path to open source
- Those practicing InnerSource enable distributed teams, essential now in the time of COVID.

**Comment by lenucksi** [comment]
Like the highlights here, added one specific.

> From discussions so far:
> 
> Speaker line-up for the Fall 2020 Summit (America) should be considered in the light of:

>  * **Different Roles**: We discuss different roles in InnerSource, should we consider representing points of views from different groups?

Given the required representation of at least three groups to get to meaningful InnerSource I argue we should represent at least:
- Engineers, 
- DevOps
- Middle Management / Line Management
- Program Management, OSPO
- Executive / Upper Management

(Also fixed broken layout in the 2nd bullet list in the comment above)

**Comment by claredillon** [comment]
I'm also going to add another one to consider: **new voices?** Should we prioritise getting a mix of new voices for the summit?

Suggesting this could be considered as new orgs represented, and/or new individuals presenting.

**Comment by claredillon** [comment]
Other consideration that was discussed as we talked about options was ISC community participation. Proposed that we make sure to have healthy representation from those that contribute regularly to ISC.

**Comment by claredillon** [comment]
Other consideration that was used in discussions: past popularity of content / theme /speaker.

**Comment by lenucksi** [comment]
> Other consideration that was discussed as we talked about options was ISC community participation. Proposed that we make sure to have healthy representation from those that contribute regularly to ISC.

The breakout overviews from last time were nice too I guess. 
How about adding in more break-out time for more interactivity?

**Comment by lenucksi** [comment]
The lightning talk time I read about plus some Q&A time could be great for this too

**Comment by claredillon** [comment]
These guidelines have been recorded in this document: https://docs.google.com/document/d/1I3d42KwwUUTWG2j3ePqIYuqKtdHWjmu0rbm6NhtsLiQ/edit?usp=sharing for ease of access to APAC summit team
