### ISSUE TITLE
Create publication strategy for Learning Path content for max reach.

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#54]
The Learning Path Working Group has asked if the Marketing WG can take a look at the following issue.

Their aim is to create a publishing strategy for Learning Path content that gives it the widest reach. 

The ask is to explore different platform options for publishing the Learning Path content and figure out if it would be (a) a good idea and (b) feasible for us to also publish our learning content there. 

Starting set of suggestions of platforms to explore:
- ISC website
- YouTube
- O'Reilly
- LinkedIn Learning
- Pluralsight

Note this is separate from the marketing strategy, which is more related to notifications/news about the content, and is not persistent in nature.

**Comment by claredillon** [comment]
Update:
@rrrutledge is exploring options with the O'Reilly learning platform. We already have the initial set of LP content on the O'Reilly platform, but exploring opportunity to put up the translations of the articles. 

Learning Path content also on YouTube at the moment.

**Comment by lenucksi** [comment]
I've applied as a lecturer for LinkedIn Learning with some of our content as examples and highlighting interest to teach our content.
- LI Learning has contracts with public libraries (Berlin public library system gets you a full LI Learning subscription for 10€/year) and quite a few corporates. Might be interesting for reach. 
- We can do Udacity Self-Service, Coursera needs separate application.

Whenever we do any of those systems we end up deep in certification / badging land because all of those things output badges / micro-credentials. We've also been offered a micro-credential for youracclaim.com sponsored by IBM.

**Comment by claredillon** [comment]
I have a request out with both Pluralsight and LinkedIn Learning to get more details about the process for authors to host there. Hoping to have update by Marketing Meeting on October 12th.

**Comment by rrrutledge** [comment]
Great, Clare!

**Comment by lenucksi** [comment]
Great, looking forward to hear the results!

**Comment by claredillon** [comment]
Early word on Pluralsight is that they are prioritising on-boarding new content/authors based on a pre-determined content schedule (and InnerSource not currently on the list). However, following up to hear more about their current priorities and and least get details of how the process works.

**Comment by rrrutledge** [comment]
Thanks for this info, Clare.

**Comment by claredillon** [comment]
Another quick update from Pluralsight. I am still due to get full update, but from early responses, I believe the following to be the case:

- They plan their content based on prioritised content schedule. Currently InnerSource not listed as a topic. In fact, I can't see any methods covered in their software dev tracks (ie. no DevOps, just tech-specific topics). 
- They have confirmed they only usually recruit individuals (not groups of people from an org).
- I believe they record Pluralsight specific content, and do not host third party materials (TBC). 

I will get more confirmation - but from these early engagements - I don't believe it makes sense to think of them as a destination for our LP material as it stands.

**Comment by lenucksi** [comment]
Thanks for the insight on Pluralsight! (bad pun of the day xD)

**Comment by claredillon** [comment]
Latest update: I have a call with Pluralsight next week to get more details of their schedule. 

Re: LinkedIn Learning - I have not got to the right people through my contacts, but there is a form to apply to be an instructor here: https://learning.linkedin.com/instructors . They do not seem to contract with groups, but rather individuals - which suggests we would have to re-record for their platform (with an individual presenter) unless they can make an exception for ISC. It is the same scenario for Pluralsight as far as I can see. Their recording guidelines are here: - https://learning.linkedin.com/content/dam/me/learning/en-us/pdfs/li-learning-instructor-toolkit-guidelines-recording-sample-video-09-19-old.pdf 

I think we definitely meet the bar in terms of quality!

I propose filling in the form on behalf of Danese - if they accept, we can discuss options for multiple presenters.

**Comment by rrrutledge** [comment]
Thanks for doing this leg work, Clare!

**Comment by claredillon** [comment]
Need to check in with Russ and the Learning Path group on this to see how the Pluralsight conversations went.

**Comment by claredillon** [comment]
@clcoffey kindly agreed to follow up on this and clarify needs/priorities for 2021.

**Comment by clcoffey** [comment]
@claredillon I have created an ISC Golden Pitch folder in the Marketing drive. could you put Danese's presentations there please :-) https://drive.google.com/drive/u/0/folders/1RQP0NgAYGO5f1MctEDyNrbEHAelbkOro

**Comment by clcoffey** [comment]
Some options for increasing the reach of the Learning Path content that came up in the Marketing Call:
- Publish it on Degreed and similar aggregator websites 
- Once we get funding we can focus on SEO
- Do more to bring our content inside organisations, such as create a feed that would allow organisations to bring the content in their internal portal. (we had a request for this already)

**Comment by clcoffey** [comment]
Clare and I have had a meeting with one company last week around bringing the LP in their organisation and we are in the requirements gathering phase. We also have a second company that has expressed an interest and we will schedule a meeting with them as well.

It is very likely this will be a long project and I won't have any concrete updates until October.

**Comment by claredillon** [comment]
Next step is to have a second requirements meeting with the other org who expressed interest in including Learning Path content on their internal InnerSource portal (not including personal details due to Chatham House Rules). We'll schedule this over the next few weeks and report back on suggestions/requirements.

**Comment by rrrutledge** [comment]
Sounds great!  Thanks, Clare.

**Comment by lenucksi** [comment]
> Next step is to have a second requirements meeting with the other org who expressed interest in including Learning Path content on their internal InnerSource portal (not including personal details due to Chatham House Rules). We'll schedule this over the next few weeks and report back on suggestions/requirements.

Feel free to send me an invite as an optional and I'll see if I can fit it in.

**Comment by clcoffey** [comment]
I have contacted Degreed with regards to including the Learning Path content on their platform however I haven't heard back from them.

Does anyone have any contacts in Degreed that might be able to help?

**Comment by claredillon** [comment]
To get more specific and move forwards with this - propose we create two new issues:
1. for the degreed investigation
2. for the requirements for pulling our learning path into internal portals

If folks agree we'll do that and close this issue

**Comment by claredillon** [comment]
Another idea is to schedule a discussion on this particular topic for one of the summit breakouts?

**Comment by rrrutledge** [comment]
Thanks for looking at this.

**Comment by clcoffey** [comment]
Latest update: Clare to introduce the Learning Path team to the company that is interested in working on Learning Path content and adopting it as training internally.

**Comment by claredillon** [comment]
Meeting scheduled for the company who is interested in incorporating this into internal portal and Learning PAth WG rep set up. Closing this long-running issue as any follow up likely to be covered in Learning Path Working Group. We can open new issues as required. 

Including here some observations/learnings through this:
- Most of the places we were initially investigating (e.g. Pluralsight / LinkedIn Learning) have a preference for content made solely for that platform and may have a paywall limiting access. Therefore, publishing on those platforms would run contrary to our goals. 
- The efforts to try and work out how this might work was actually quite time consuming, and different by platform - so the effort probably wouldn't easily scale. 
- This issue in general got de-prioritized as the marketing working group took on more activities (e.g. organizing summits / additional community calls)... it was not seen to be urgent. This was partially due to the fact that there was an increase in engagement in the learning path as a secondary outcome of increased engagement with ISC (through the other reach activities). So focus on the broader reach goal delivered the growth in usage to some respect. 
- The original goal of trying to have more impact by getting more folks to use the Learning Path is still a good one. I propose that we re-visit the question over time and look for easier-to implement ideas and check to see whether it becomes a higher priority. I will start a discussion where we can gather ideas for posterity. 

Closing this issue for now.

**Comment by claredillon** [comment]
Discussion around this issue is now at: https://github.com/InnerSourceCommons/InnerSourceMarketing/discussions/147
