### ISSUE TITLE
Agree ticketing system

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#63]
We wish to use EventYay. But need the following:
- a bank account (if we don't Event Yay doesn't handle the billing).

**Comment by lenucksi** [comment]
What's the status on the open issues we had last time? We still have a standing offer from Hong Phuc to help us with what we might have issues with. 
One offer was to show us around everything EventYay offers and have that recorded which would bring knowledge to us and a re-usable explanatory video to them.

From what I've seen and heard there's also integration regarding schedule and cfp result selection. We might be interested in that too as it could reduce a bit our work. There's even fancy apps for presenters, organizers and visitors if I got it right.

**Comment by claredillon** [comment]
@lenucksi a walkaround would be really great. It would help us explain the issues we encountered. 

Worth noting the most fundamental blocker is that we need something that takes care of the billing while we don't have an ISC account (because it is inappropriate to use PayPal with a personal account, as the "receipt" doesn't reference the summit, and looks like a personal payment. 

But assuming we get our bank account soon... the secondary issue was the fact that the ticketing process didn't complete for some of us using the test event. 

Secondary priority is the ability to easily manage attendee mailings etc.

The CFP process would be really interesting too, but hasn't been too bad doing it the way we do it now.

It would be super to work through this with Hong Phuc. I'll start a thread on Slack to schedule.
