### ISSUE TITLE
Add a Marketing & Outreach WG page to the ISC website

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#67]
From Clare.
What is the purpose of this?
Do all other WGs have such pages?

**Comment by spier** [comment]
@claredillon what type of information would you like to share on the ISC website about the WG?

e.g. for the Patterns WG I am only aware of this page here: https://innersourcecommons.org/resources/patternsofficehours/
All other things happen in Slack and the GitHub repo.

**Comment by claredillon** [comment]
This was done as part of the website update in Q1 2021
