### ISSUE TITLE
Set up monthly reporting to other WGs

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#68]
From Clare.
Could this be covered with the reports that we are creating for the Board now?

**Comment by spier** [comment]
@claredillon can you please elaborate on the purpose of this idea?

Also could we get by at the moment by using the reports that we generate for the for Board, i.e. we would share the exact same report with the other WGs?

**Comment by claredillon** [comment]
Agreed - that we share the reports for the board to the other groups. Closing this as a result. Learning Path sometimes also adds a discussion of this to the agenda - it is nice if someone from the Marketing WG can go along to those LP meetings, in case there are questions.
