### ISSUE TITLE
Move ideas into issues

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#77]
To make it easier to use the Board, I decided to get rid of the "ideas" column. That column contained a lot of short notes, that did not seem detailed enough for anybody to actually pick them up.

I converted all of these ideas/notes into full issues, and labeled them with "clarification needed":
https://github.com/InnerSourceCommons/marketing-wg/labels/clarification%20needed

I have also contacted the authors of these ideas/notes with the hope that they can elaborate a bit further on the idea. 

Next steps (Proposal):

- wait for the idea authors to provide further information on the ideas
- then remove the "clarification needed" label from the issue
- add the issue to the "To Do" column of our board again

**Comment by claredillon** [comment]
Question around this:
I had the notion that the "Ideas" column was a place to capture ideas before we had decided it was the right time "to do" them. Moving from Idea to ToDo was an indication we actually wanted it done. Be great to discuss this scenario to make sure we have a way to differentiate between all the things we can do, and all the things we deem next most important things "to do".

Related to this - is there a place/way to designate things that still need work, but have been de-prioritized due to other things gaining priority / not enough resources / blocked etc.?

**Comment by spier** [comment]
Of course there are many ways to do these things :) 
I am biased by how I would work in an Agile software development team. So not sure if this can work for an open source project in similar ways. So please consider that bias when reading the following.

My general thoughts about these topics are:
- don't worry about loosing things. If an idea is good, it will come back.
- keep the ToDo column small enough. an ever growing list of ToDos is demotivating and will make it harder to focus on what is important/urgent and what is not
- regularly clean up the backlog (reviewing all open issues; what is in ToDo, etc)

My recommendation for Ideas:
- create regular Issues for Ideas
- add a new label called "Idea" to the issues, to clearly mark them as "not ready for ToDo yet"
- every once in a while do a Grooming session with the team where you go through the "Idea" issues. 
  - Add enough detail to the issue, so that this can be picked up by other people. Then "Idea" and move it to the ToDo column
  - If there is no consensus that people support this Idea, then add the results of that conversation to the Issue as a comment to the issue and close the Issue

My recommendation for de-prioritized things:
- create regular Issues for these
- move them to the very bottom of the ToDo column (potentially marking them with an extra label "Deprioritized" or similar)
- every once in a while do a Grooming session with the team where you go through the "Deprioritized" issues where you decide what you want to do with them (similar to the explanation above) 

Doing so would also show if the group spends too much time on generating new ideas, and too little time on actually implementing them. That is also a healthy reality check for most groups :)

**Comment by dicortazar** [comment]
Question here: I was supposed to move tickets into the new project (tons of thanks for opening this). Did you define a specific process yesterday? Or I simply go and start creating / moving (not sure if I can do it) tickets?

I think this is aligned to this conversation as the Ideas column is moved to tickets according to this discussion. Please let me know if this is not the case and I move this conversation to another place.
