### ISSUE TITLE
Create new open and transparent repository for marketing

### ISSUE THREAD

**Issue by dicortazar** [InnerSourceCommons/InnerSourceMarketing#78]
### Create new open and transparent repository for marketing

After today's meeting, and previous discussions last weeks, the idea is to be much more open and transparent in the marketing working group. The goal here is to have a better on boarding process for newcomers and have more open discussions without the process of adding everyone to this private repo.

The idea is to move / copy some of the existing open issues at least to the new place. We can not open this one as this already contains private info, or info under Chatham House Rule.

### Acceptance Criteria

Repository is open, and tickets are moved into there (at least open tickets).

As measure of success, this should take place and we should recheck how many new tickets we needed to open in the new open and public working group and this one. If the number of private issues is not that big, we may consider moving into a lighter list of tasks through the use of Google Docs meetings or keep working in this way.

### Help Needed / Blockers

Second review would be great to have.

**Comment by claredillon** [comment]
I believe we can make this board open. In preparation - I have reviewed each of the issues on the three boards here to ensure nothing sensitive was being referenced. I think we can make this board public - should save a lot of moving issues! 

A couple of related ideas/questions:
- Propose we change name to InnerSourceMarketing to be consistent with the other WG repo names.
- Question on how to indicate the difference between people having ideas and the ones the Marketing WG want "to do". There will always be more ideas that what we want to do - so we should have a way to capture "half baked" ideas for review every now and then, without committing them to a "to do" list. 
- related: how do we indicate that work is still to be done, but it has been stalled for some reason or other.

**Comment by claredillon** [comment]
Update:
- We have made the old Marketing WG Board public.
- After discussion with project board norms with David, we created an Ideas column to make a clear differentiation between things which we haven't yet decided we want to do, and those we actively want to do. 
- Regarding things that are stalled/blocked - we agreed to create labels to identify those - but best practice is to try and move everything in progress forward. 

Outstanding:
- Should we rename to InnerSourceMarketing for consistency with other groups? Does it matter?

**Comment by spier** [comment]
The new repository is now available here:
https://github.com/InnerSourceCommons/marketing-wg

@claredillon wants to rename the old repo, and then this issue is done.

**Comment by dicortazar** [comment]
This is great, thanks a lot!

**Comment by claredillon** [comment]
Old repo renamed and made private. This repo renamed for consistency.
