### ISSUE TITLE
Publish State of InnerSource Report on the website

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#79]
### Purpose & Details

With the State of InnerSource report, we would like to research, document and showcase the adoption of InnerSource. This report will be featured on the Research Page (to come on the website) and will be used to accelerate the adoption of InnerSource. 

The report will be based on the research conducted by Tapajit Dey.

Resources:
Tapajit's overview of the latest survey: https://www.youtube.com/watch?v=-XWBzcYuvxA
The results summary (see links at the top for more details): https://tapjdey.github.io/InnerSource_Survey_2020/index.html
2016 survey: https://innersourcecommons.net/assets/files/InnerSourceCommonsSurvey2016.pdf

### Acceptance Criteria

- [x] We have produced the first State of InnerSource report draft in Google Slides. 
- [x] We have shared the document with the Marketing group in Slack and on the Marketing Call for the purpose of receiving feedback
- [x] We have implemented the feedback 
- [x] We have designed the document to look and feel in line with the InnerSource Brand
- [x] Publish into the website

### Help Needed / Blockers

- We need help from people providing feedback on the content of the document.

**Comment by clcoffey** [comment]
Link to the first draft of the State of InnerSource 2020 report: https://docs.google.com/presentation/d/1i2c_r4hILUV6B67R_AxG_9FapnoTDsnuyXl1J2jE9Hc/edit?usp=sharing

Please note that this document only contains the content and still needs to be designed to include the ISC brand.
Please provide any feedback you might have on the content in comments on the document or in the comments below.

**Comment by clcoffey** [comment]
Feedback from Tapajit Dey

Comments on the presentation - slide 9: instead of so many numbers in the size chart data, do you think the boxplot-violin plot combo from https://tapjdey.github.io/InnerSource_Survey_2020/company.html be easier to understand?
Slide 15 - Just realized the X-axis labels are wrong - these are points in the likert scale, not years - could you perhaps crop out the X-axis labels?
Slide 16, 17 - are those gray bars there by design?
Slide 27 - Maybe you can highlight the apparent contrast between people feeling that Management won’t value their InnerSource contributions vs. in Slide 23 that states that most people say management supports their InnerSource work

**Comment by clcoffey** [comment]
@claredillon  Changes made as per Tapajit's feedback. Document ready for Design.

**Comment by voborgus** [comment]
Linked with https://github.com/InnerSourceCommons/innersourcecommons.org/issues/77

**Comment by clcoffey** [comment]
@spier I've attached the latest version of the State of InnerSource research document that has been designed & prettified.
[State of InnerSource Report 2020.pdf](https://github.com/InnerSourceCommons/InnerSourceMarketing/files/6849435/State.of.InnerSource.Report.2020.pdf)

**Comment by dicortazar** [comment]
@spier anything we can help with, please let us know ;).

**Comment by spier** [comment]
@dicortazar I am getting started on this now.

You could help with feedback on these questions:
- where to put the surveys? I currently have it at `/learn/surveys/`.
- which image could we use as preview image that could e.g. be shown at https://innersourcecommons.org/learn/?

**Comment by spier** [comment]
Also do we want individual pages for each survey? i.e. one page for 2016 and one for 2020.

I think we don't need that and can just use a single page under `/learn/surveys` where we list both surveys, as we only have 2 surveys right now anyways. We can change this in the future if more surveys are created.

**Comment by clcoffey** [comment]
I think you are right, one page listing both documents should be fine. I would call it Research rather than surveys though and I think you are right to put it under Learn.

**Comment by claredillon** [comment]
I'll note that @user-group (Klaas) mentioned he might add additional research papers to the Research page once it is in place. So just flagging this issue for his attention.

**Comment by spier** [comment]
Thanks for the feedback @clcoffey. I renamed it to `/learn/research`.
You can review the implementation at https://github.com/InnerSourceCommons/innersourcecommons.org/pull/146

**Comment by spier** [comment]
The surveys are now published here https://innersourcecommons.org/learn/research/

Moving this story to Ready for Review, so that we can check it out at the next meeting.

**Comment by claredillon** [comment]
Great to have a Research page live again - thanks @spier and @clcoffey (and of course Tapajit for the original research! :)
