### ISSUE TITLE
ISC Autumn Summit 2020 - decide location/date.

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#8]
Finalise date and "location" for Autumn summit. If virtual, "location" implies host.

**Comment by lenucksi** [comment]
- We need a sponsor
- We need an internal lead organizer

- This one is going to be virtual, 
- The current co-location gave people an incentive due to lifting their local boats with the conference tide. We don't have that with the virtual one.

**Comment by lenucksi** [comment]
- September 15./16. is likely the date
- We're going to be virtual again
- Summit planning committee will be raised and dealing the details. 
Add link to it once it became active.
