### ISSUE TITLE
Community Call Takeaways

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#80]
### Purpose & Details

Create a shareable list of insights from our June Community Call discussion. These insights will be used to create content for our social channels. 

### Acceptance Criteria

- [x] We have produced an article detailing the takeaways from the community call in Google Drive.
- [x] We have shared the draft in the Marketing channel on Slack asking people to contribute/ provide feedback on the document
- [x] We have implemented the feedback
- [x] We have created the article on LinkedIn and shared it with InnerSource Commons
- [x] We have produced an infographic based on the content in the article.
- [x] We have shared the infographic for review on the Marketing channel
- [x] We have implemented the feedback received
- [x] We have shared the infographic on Twitter and LinkedIn.

### Help Needed / Blockers

- Feedback is needed from the community on the document and infographic created.

**Comment by clcoffey** [comment]
The first draft of the  takeaways document is here: https://docs.google.com/document/d/1Lbky5brsEAAF6RN6tpoGLXbooGYfj-AKK44VGrWGTDA/edit?usp=sharing 

@Katiegilroyy I added you to this task as you usually produce the Infographic. I hope that's ok.

**Comment by clcoffey** [comment]
@Katiegilroyy did you get the chance to share the infographic?

**Comment by Katiegilroyy** [comment]
Yeah posted on social medias

**Comment by clcoffey** [comment]
Great! I'll close this issue then :-)
