### ISSUE TITLE
Gather feedback on 2021 Summit plans

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#84]
Put a questionnaire out to the community in Slack about the Summit.

**Comment by claredillon** [comment]
A discussion document has been shared in the Marketing Slack channel. Once we get feedback at the Marketing meeting, I will share in General channel for comment / feedback etc.

**Comment by claredillon** [comment]
Noting that a questionnaire might not be the right tool to gather the feedback required - so proposing the doc as a way to gather richer input.

**Comment by claredillon** [comment]
APAC Marketing meeting set up for July 15th, 8am UTC

**Comment by dicortazar** [comment]
Discussion and open document will be shared in the general Slack channel by @claredillon.
