### ISSUE TITLE
Creating an Issue Automation

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#85]
### Purpose & Details

With this automation, we want to give any newcomer to the marketing group the opportunity to contribute and for their contribution to be recognised. For this, we have created the ["Social following and share"](https://github.com/InnerSourceCommons/marketing-wg/issues/81) issue and labelled it as "good first issue"

When someone is interested in doing this issue they can assign it to themselves, carry out the work and then close the issue.

Upon closing the issue, however, we would like for the issue to be re-created, to give other people the opportunity to contribute as well. With this in mind, we have created an issue template: "Social following and share" and are currently asking the person that closed the previous issue to re-create it by using this template.

It would be great if the re-creation of the issue could be automated.

### Acceptance Criteria

- when the current issue is Closed, a new issue should be created by using the provided template.
- the issue should be labelled "good first issue"
- the issue should be part of the "Marketing WG Board" project
- the issue should be triaged in the To-Do Column within the project

### Help Needed / Blockers

I am not too sure if this is entirely possible so I need someone that knows Github Automations to advise.

**Comment by spier** [comment]
I can try to do the automation piece here.

The questions are:
a) automatically create a new issue (based on a template), whenever a given old issue is closed - e.g. an "an evergreen issue"
b) if a new issue is created, how to move it to a given board automatically?

**Comment by spier** [comment]
@clcoffey I think this is what you want wrt creating the evergreen issue for "Social following and share" whenever the previous issue is closed.

Just close the issue that is there now, and see how a new one is created:
https://github.com/spier/gha-auto-issue-creation/issues

If this is how you expected this to work, I can integrate the respective GitHub Action into our repo here.
