### ISSUE TITLE
Add issues to project boards automatically

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#87]
In the last Marketing WG call in heard a need to add new issues to our project boards automatically.

I have prototyped this here: https://github.com/spier/gha-auto-project-assignment

To try it out:
- create a new issue using one of the two issue templates
- wait a bit
- then see your new issue appear on the correct board

I don't know if this is roughly what you wanted?

Let me know what your requirements are and I can see if I can adapt it, and then port the functionality in to this repo here.

**Comment by spier** [comment]
@clcoffey I think you had mentioned this? Could you share more about how you would want this to work?

**Comment by clcoffey** [comment]
Yes, is there a way to connect the template to the board? So when creating a template specifying that any issue created by using this template should be added to this specific board automatically.

I think this is mostly a methodology that we are looking for rather than someone to do it for us as we haven't created all the templates yet.

So if we could have a step by step document that someone could go through when they create a template it would be great.

**Comment by spier** [comment]
The way that I thought this might work is by having specific labels, that would indicate what project it should go to i.e.
- project_a
- project_b

We would set these labels on the specific templates (as you have already done with the "good first issue" label for example). So a new issue created based on that template would then create such a label indicating the project.

You can see that approach in action here:
- https://github.com/spier/gha-auto-project-assignment
- create an issue based on the existing templates, and then you should see the issues shown up on the respective project boards

Writing a step by step instruction is actually harder for me than just doing it (as I have already prototyped it).
Of course that has the disadvantage that you might not be able to adapt thing son your own.

However it would still vote for setting things up once and trying it out. Who knows, maybe we don't even like that approach and then we can throw it all away :)

So maybe we should move this card back to "To do" and wait until we have a 2nd project in this marketing-wg? Because this auto-project-assignment approach would only become relevant then, right?

**Comment by dicortazar** [comment]
@clcoffey will take the lead in the task and discuss with @Katiegilroyy about next steps

**Comment by clcoffey** [comment]
@spier I just saw your comment now. Sorry for the late reply. 

I think you are right, this will become relevant when we start organising the Summit, probably in September.

**Comment by spier** [comment]
Sounds good.
Let's look at it again in September then.

**Comment by clcoffey** [comment]
It seems like we haven't been too consistent in creating issues around the summit last November. I think we should park this for the moment.
