### ISSUE TITLE
Make ISC website and tools GDPR Compliant

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#9]
We need to make sure our comms and website are GDPR compliant. This includes storage of email PPI from things like event registration and newsletters as well as necessary privacy statements etc.

**Comment by lenucksi** [comment]
For now the following should be okay-ish for now:
- Imprint
- Privacy Policy
- Ensure Cookie-Freeness to save us the Cookie-Tool
- Think about getting a hold of the Auftragsdatenverarbeitungsvertrag from GitHub for our web hosting

Our mailing et al is a different thing.

Once we Go for web analytics et al. we're back to previous squares regarding cookie compliance or other madness.

**Comment by claredillon** [comment]
Work done as part of website update in Q1 2020
