### ISSUE TITLE
YouTube Playlist for the recordings of the Community Calls

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceMarketing#94]
### Title

YouTube Playlist for the recordings of the Community Calls

### Purpose & Details

Our Community Calls created new InnerSource-related content for anybody interested on a regular cadence.

Let's make it as easy as possible for interested people to find the recordings of the Community Calls.
e.g. by creating a dedicated playlist under https://www.youtube.com/c/InnerSourceCommons/playlists

### Acceptance Criteria

When somebody asks "Where can I listen/watch the latest Community Calls, we should have a URL that we can point them to.

### Help Needed / Blockers

Not sure who can create playlists on your YouTube account?

**Comment by spier** [comment]
Looks like somebody started this already?
https://www.youtube.com/playlist?list=PLCH-i0B0otNR90HDn8D9PsnQNE1r3JiUE

**Comment by clcoffey** [comment]
Is it ok if I close this? Or do you think something else should be done to finalise this issue?

**Comment by spier** [comment]
Nothing left to do here.
Closing.
